import { createClient } from '@supabase/supabase-js';

const sb = createClient(
  'https://alazsyhlydhimfqpdros.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYXpzeWhseWRoaW1mcXBkcm9zIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODYzNDcyMSwiZXhwIjoyMDk0MjEwNzIxfQ.Veyo2POB-egtBhQSCewegNpj6ucYZ8f2Tt8Q0yKJCRo'
);

const BM = [
  // ── AMINOSÄUREN ─────────────────────────────────────────────────────────────
  {slug:'tryptophan',name:'Tryptophan',aliases:['tryptophan','trp','l-tryptophan'],description:'Essentielle Aminosäure und einzige Vorstufe für Serotonin und Melatonin. Bei Entzündung wird Tryptophan über IDO in Kynurenin umgeleitet – weniger Serotonin trotz ausreichender Zufuhr.',symptoms:['Depression','Schlafstörung','Erschöpfung','Angst','Stimmungsschwankungen'],cofaktoren:[{name:'Vitamin B6 (P5P)',why:'Cofaktor der Tryptophan-Hydroxylase'},{name:'Magnesium',why:'Moduliert IDO-Aktivität'}]},
  {slug:'leucin',name:'Leucin',aliases:['leucin','leucine','bcaa'],description:'Verzweigtkettige Aminosäure (BCAA) – stärkster Aktivator der mTOR-Proteinsynthese. Essenziell für Muskelaufbau und -erhalt.',symptoms:['Muskelabbau','Erschöpfung','Gewichtsverlust','Schwäche'],cofaktoren:[{name:'Vitamin B6',why:'Cofaktor des BCAA-Stoffwechsels'},{name:'Magnesium',why:'Cofaktor der Transaminasen'}]},
  {slug:'isoleucin',name:'Isoleucin',aliases:['isoleucin','isoleucine','bcaa'],description:'BCAA mit Rolle in Energiegewinnung und Hämoglobin-Synthese. Reguliert Blutzucker und fördert Muskelglukoseaufnahme.',symptoms:['Blutzuckerschwankungen','Erschöpfung','Muskelabbau'],cofaktoren:[{name:'Vitamin B6',why:'Aminosäure-Stoffwechsel'}]},
  {slug:'valin',name:'Valin',aliases:['valin','valine','bcaa'],description:'Drittes BCAA – essenziell für Gewebereparatur, Nervenfunktion und Energiegewinnung im Muskel.',symptoms:['Muskelabbau','Erschöpfung','Konzentrationsprobleme'],cofaktoren:[{name:'Vitamin B6',why:'Transamination'}]},
  {slug:'methionin',name:'Methionin',aliases:['methionin','methionine','sam','methylierung'],description:'Schwefelhaltige Aminosäure, Startpunkt des Methylierungszyklus (SAM-Synthese) und Vorläufer von Cystein, Taurin und Glutathion.',symptoms:['Leberproblem','Erschöpfung','Depressive Stimmung','Haarausfall'],cofaktoren:[{name:'Folsäure',why:'Methylierungszyklus'},{name:'Vitamin B12',why:'Homocystein-Abbau'}]},
  {slug:'phenylalanin',name:'Phenylalanin',aliases:['phenylalanin','phenylalanine','phe'],description:'Essentielle Aminosäure, Vorläufer von Tyrosin, Dopamin, Adrenalin und Noradrenalin. Phenylketonurie-Screening-Marker.',symptoms:['Antriebslosigkeit','Brain Fog','Stimmungstief'],cofaktoren:[{name:'Vitamin B6',why:'Hydroxylierung zu Tyrosin'},{name:'Eisen',why:'Cofaktor der Phenylalaninhydroxylase'}]},
  {slug:'tyrosin',name:'Tyrosin',aliases:['tyrosin','tyrosine','tyr'],description:'Direkte Vorstufe von Dopamin, Noradrenalin, Adrenalin und Schilddrüsenhormonen. Wird aus Phenylalanin synthetisiert.',symptoms:['Antriebslosigkeit','Konzentrationsprobleme','Schilddrüsenproblem','Depressive Stimmung'],cofaktoren:[{name:'Vitamin B6',why:'DOPA-Decarboxylase'},{name:'Eisen',why:'Tyrosinhydroxylase-Cofaktor'}]},
  {slug:'threonin',name:'Threonin',aliases:['threonin','threonine','thr'],description:'Essentielle Aminosäure, Vorläufer von Glycin und Serin. Wichtig für Kollagensynthese, Immunfunktion und Darmbarriere.',symptoms:['Wundheilungsstörung','Immunschwäche','Darmprobleme'],cofaktoren:[{name:'Vitamin B6',why:'Threonin-Aldolase'}]},
  {slug:'lysin',name:'Lysin',aliases:['lysin','lysine','lys'],description:'Essentielle Aminosäure für Kollagen-Crosslinking, Carnitin-Synthese und antivirale Wirkung (hemmt Herpes-Replikation).',symptoms:['Häufige Herpes-Ausbrüche','Erschöpfung','Wundheilungsstörung','Haarausfall'],cofaktoren:[{name:'Vitamin C',why:'Kollagensynthese mit Lysin'},{name:'Eisen',why:'Carnitin-Synthese'}]},
  {slug:'arginin',name:'Arginin',aliases:['arginin','arginine','arg','no-synthese'],description:'Halbessenzielle Aminosäure – Substrat der NO-Synthase (Stickstoffmonoxid) für Gefäßerweiterung. Wichtig für Immunfunktion und Wundheilung.',symptoms:['Bluthochdruck','Durchblutungsstörung','Potenzprobleme','Wundheilungsstörung'],cofaktoren:[{name:'Zink',why:'Arginase-Cofaktor'},{name:'Vitamin B6',why:'Harnstoff-Zyklus'}]},
  {slug:'glutamin',name:'Glutamin',aliases:['glutamin','glutamine','gln'],description:'Häufigste Aminosäure im Blut. Hauptbrennstoff der Darmzellen – essenziell für Darmbarriere-Integrität, Immunzellen und Leberfunktion.',symptoms:['Leaky Gut','Darmprobleme','Immunschwäche','Muskelabbau nach Sport'],cofaktoren:[{name:'Magnesium',why:'Glutaminsynthase-Cofaktor'}]},
  {slug:'glycin',name:'Glycin',aliases:['glycin','glycine','gly'],description:'Kleinste Aminosäure, hemmender Neurotransmitter. Cofaktor der Glutathionsynthese, Kollagenbestandteil (33%), Vorläufer von Kreatin und Häm.',symptoms:['Schlafstörung','Muskelverspannung','Gelenkprobleme','Angst'],cofaktoren:[{name:'Serin',why:'Gegenseitige Konversion über Serin-Hydroxymethyltransferase'}]},
  {slug:'serin',name:'Serin',aliases:['serin','serine','ser'],description:'Aminosäure für Phospholipidsynthese (Phosphatidylserin), Myelinsynthese und Neurotransmitter-Vorstufe (D-Serin an NMDA-Rezeptoren).',symptoms:['Brain Fog','Konzentrationsprobleme','Nervenschäden'],cofaktoren:[{name:'Folsäure',why:'Serin-Glycin-Interkonversion'}]},
  {slug:'alanin',name:'Alanin',aliases:['alanin','alanine','ala'],description:'Wichtigste glukogene Aminosäure – transportiert Stickstoff aus Muskeln zur Leber (Alanin-Glukose-Zyklus). Blutzucker-Regulator bei Fasten.',symptoms:['Blutzuckerschwankungen','Erschöpfung','Muskelschwäche'],cofaktoren:[{name:'Vitamin B6',why:'Transaminierung'}]},
  {slug:'taurin',name:'Taurin',aliases:['taurin','taurine','tau'],description:'Schwefelhaltige Aminosäure für Gallensäure-Konjugation, Herzrhythmus, Augengesundheit und GABA-Potenzierung. Wirkt osmoregulatorisch in Herz und Gehirn.',symptoms:['Herzrhythmusstörungen','Angst','Augenprobleme','Muskelkrämpfe'],cofaktoren:[{name:'Vitamin B6',why:'Cysteinsulfinsäure-Decarboxylase'},{name:'Zink',why:'Taurin-Transporter'}]},
  {slug:'citrullin',name:'Citrullin',aliases:['citrullin','citrulline','no-marker'],description:'Marker für Stickstoffmonoxid-Produktion und Dünndarmzellen-Integrität. Niedrige Werte zeigen SIBO, Darmschleimhautschaden oder Arginase-Überaktivität.',symptoms:['Bluthochdruck','SIBO','Darmprobleme','Erschöpfung'],cofaktoren:[{name:'Arginin',why:'NO-Synthase-Substrat'}]},
  {slug:'ornithin',name:'Ornithin',aliases:['ornithin','ornithine','orn','harnstoffzyklus'],description:'Harnstoffzyklus-Intermediat. Ornithin-Überschuss bei Hyperammonämie, Mangel bei Leberbelastung. Fördert Wachstumshormon-Ausschüttung.',symptoms:['Erschöpfung','Leberproblem','Schlafstörung'],cofaktoren:[{name:'Arginin',why:'Harnstoffzyklus'}]},
  {slug:'homocystein',name:'Homocystein',aliases:['homocystein','homocysteine','hcy','methylierung'],description:'Toxisches Intermediat des Methionin-Stoffwechsels. Erhöhte Werte schädigen Gefäßwände, erhöhen Herzinfarkt- und Demenzrisiko. Wichtigster Methylierungs-Marker.',symptoms:['Herzerkrankung','Demenz','Schlaganfall','Thrombose','Depression'],cofaktoren:[{name:'Vitamin B12',why:'Remethylierung'},{name:'Folsäure',why:'MTHFR-Weg'},{name:'Vitamin B6',why:'Transsulfurierung'}]},
  {slug:'histidin',name:'Histidin',aliases:['histidin','histidine','his','histamin-vorstufe'],description:'Essentielle Aminosäure, Vorläufer von Histamin. Wichtig für Wundheilung, Myelin und Säure-Basen-Puffer (Hämoglobin).',symptoms:['Nahrungsmittelreaktion','Histaminunverträglichkeit','Anämie'],cofaktoren:[{name:'Zink',why:'Histidinase-Aktivität'}]},
  // ── NEUROTRANSMITTER ────────────────────────────────────────────────────────
  {slug:'dopamin',name:'Dopamin',aliases:['dopamin','dopamine','dopa','motivation'],description:'Neurotransmitter für Motivation, Antrieb und Belohnung. Wird aus Tyrosin über L-DOPA synthetisiert – abhängig von B6, Eisen und BH4.',symptoms:['Antriebslosigkeit','Prokrastination','ADHS','Freudlosigkeit','Konzentrationsprobleme'],cofaktoren:[{name:'Vitamin B6 (P5P)',why:'DOPA-Decarboxylase'},{name:'Eisen',why:'Tyrosinhydroxylase'},{name:'Magnesium',why:'BH4-Stabilisierung'}]},
  {slug:'serotonin',name:'Serotonin',aliases:['serotonin','5-ht','5-htp'],description:'95% im Darm produziert. Reguliert Stimmung, Schlaf und Appetit. Bei Darmdysbiose oder Entzündung (IDO-Aktivierung) sinkt Serotonin trotz guter Ernährung.',symptoms:['Depression','Stimmungsschwankungen','Schlafstörung','Heißhunger auf Süßes','Reizbarkeit'],cofaktoren:[{name:'Tryptophan',why:'Einzige Vorstufe'},{name:'Vitamin B6',why:'Aromatische Decarboxylase'},{name:'Magnesium',why:'Tryptophan-Hydroxylase'}]},
  {slug:'gaba',name:'GABA',aliases:['gaba','gamma-aminobuttersäure'],description:'Wichtigster hemmender Neurotransmitter. Beruhigt das Nervensystem, fördert Schlaf und reduziert Angst. Wird aus Glutamat via Glutamat-Decarboxylase (B6-abhängig) gebildet.',symptoms:['Innere Unruhe','Angststörung','Einschlafprobleme','Übererregbarkeit','Burnout'],cofaktoren:[{name:'Vitamin B6 (P5P)',why:'Glutamat-Decarboxylase (GAD)'},{name:'Magnesium',why:'GABA-A-Rezeptor-Modulator'},{name:'Taurin',why:'Potenziert GABA-Wirkung'}]},
  {slug:'glutamat',name:'Glutamat',aliases:['glutamat','glutamate','glu','exzitatorisch'],description:'Wichtigster erregender Neurotransmitter – Gegenspieler von GABA. Glutamat-GABA-Gleichgewicht entscheidend bei Angst, Schlaf und Epilepsie.',symptoms:['Übererregbarkeit','Angst','Schlafstörung','Migräne','Epilepsie'],cofaktoren:[{name:'Magnesium',why:'Blockiert NMDA-Rezeptoren bei Übererregung'},{name:'Zink',why:'NMDA-Rezeptor-Modulator'}]},
  {slug:'adrenalin',name:'Adrenalin',aliases:['adrenalin','epinephrin','epinephrine'],description:'Stresshormon der Nebenniere. Aktiviert Herzfrequenz, Blutdruck und Energiemobilisierung im Notfall. Bei Burnout chronisch erhöht → Erschöpfung.',symptoms:['Herzrasen','Panikattacken','Schlafstörung','Erschöpfung','Burnout'],cofaktoren:[{name:'Vitamin C',why:'Dopamin-β-Hydroxylase'},{name:'Kupfer',why:'Dopamin-β-Hydroxylase'}]},
  {slug:'noradrenalin',name:'Noradrenalin',aliases:['noradrenalin','norepinephrin','norepinephrine'],description:'Neurotransmitter für Aufmerksamkeit, Konzentration und Blutdruck. Hauptregulator des präfrontalen Cortex. Mangel bei ADHS und Depression.',symptoms:['Konzentrationsprobleme','Brain Fog','ADHS','Antriebsmangel','Chronischer Stress'],cofaktoren:[{name:'Vitamin B6',why:'Biosynthese'},{name:'Kupfer',why:'Dopamin-β-Hydroxylase'}]},
  {slug:'melatonin',name:'Melatonin',aliases:['melatonin','schlafhormon'],description:'Schlafhormon der Zirbeldrüse. Reguliert circadianen Rhythmus, schützt Mitochondrien antioxidativ. Produktion ab 21 Uhr – gehemmt durch blaues Licht.',symptoms:['Schlafstörung','Einschlafprobleme','Durchschlafprobleme','Tagesmüdigkeit','Jetlag'],cofaktoren:[{name:'Tryptophan→Serotonin',why:'Serotonin ist direkter Melatonin-Vorläufer'},{name:'Magnesium',why:'HIOMT-Enzym (letzte Synthese-Stufe)'}]},
  {slug:'ido-aktivitaet',name:'IDO-Aktivität (Kynurenin/Tryptophan-Quotient)',aliases:['ido','indolamin-2,3-dioxygenase','kyn/trp'],description:'IDO-Enzym leitet bei Entzündung Tryptophan in den Kynurenin-Weg um → weniger Serotonin, mehr Quinolinsäure. Erhöhter IDO-Index ist Marker für Neuroinflammation.',symptoms:['Depression','Chronische Erschöpfung','Schlafstörung','Neuroinflammation'],cofaktoren:[{name:'Curcumin',why:'Hemmt IDO-Aktivierung'},{name:'NAC',why:'Reduziert inflammatorische IDO-Induktion'}]},
  // ── HORMONE ─────────────────────────────────────────────────────────────────
  {slug:'cortisol-morgens',name:'Cortisol (morgens)',aliases:['cortisol morgens','morgencortisol','cortisol 8 uhr'],description:'Cortisol-Morgenwert ist der wichtigste HPA-Achsen-Marker. Physiologisch am höchsten 30 Min nach dem Aufwachen (CAR – Cortisol Awakening Response).',symptoms:['Morgenmüdigkeit','Erschöpfung','Burnout','Erschöpfung morgens'],cofaktoren:[{name:'Vitamin C',why:'Nebennierenmark braucht höchste VC-Konzentration'},{name:'Magnesium',why:'Puffert Cortisol-induzierte Kalziumüberladung'}]},
  {slug:'cortisol-mittags',name:'Cortisol (mittags)',aliases:['cortisol mittags','mittagscortisol'],description:'Zweiter Messzeitpunkt des Cortisol-Tagesprofils. Zeigt den physiologischen Abfall nach dem Morgengipfel.',symptoms:['Energieeinbruch mittags','Konzentrationsprobleme','Burnout'],cofaktoren:[{name:'Vitamin C',why:'Nebennierenunterstützung'}]},
  {slug:'cortisol-abends',name:'Cortisol (abends)',aliases:['cortisol abends','abendcortisol','cortisol 20 uhr'],description:'Abendcortisol sollte niedrig sein. Erhöhtes Abendcortisol blockiert Melatonin-Produktion → Einschlafprobleme. Zeigt invertiertes Cortisol-Profil.',symptoms:['Einschlafprobleme','Wired-but-Tired','Gedankenrasen nachts','Burnout'],cofaktoren:[{name:'Magnesium',why:'Senkt Abendcortisol'},{name:'Ashwagandha',why:'Adaptogen – normalisiert Cortisol-Kurve'}]},
  {slug:'dhea',name:'DHEA',aliases:['dhea','dehydroepiandrosteron','dheas'],description:'Nebennierenhormon und Vorläufer von Testosteron + Östrogen. Wichtigster Anti-Aging-Marker der Nebennierenreserve. Fällt nach 25 Jahren natürlich ab.',symptoms:['Erschöpfung','Libidoverlust','Immunschwäche','Muskelabbau','Kognitive Abnahme'],cofaktoren:[{name:'Vitamin D',why:'Stimuliert DHEA-Synthese'},{name:'Zink',why:'Steroidhormonsynthese'}]},
  {slug:'testosteron',name:'Testosteron',aliases:['testosteron','testosterone','freies testosteron'],description:'Hauptandrogen. Reguliert Muskelmasse, Libido, Knochen und Stimmung. Chronischer Stress (Cortisol-Anstieg) supprimiert Testosteron direkt.',symptoms:['Libidoverlust','Muskelabbau','Erschöpfung','Bauchfett','Erektionsprobleme','Antriebslosigkeit'],cofaktoren:[{name:'Zink',why:'Hemmt Aromatase (Testosteron→Östrogen)'},{name:'Vitamin D',why:'Leydig-Zellen brauchen Vitamin D für Testosteron-Synthese'}]},
  {slug:'estradiol',name:'Estradiol (E2)',aliases:['estradiol','östradiol','e2','östriol'],description:'Stärkstes Östrogen. Reguliert Menstruationszyklus, Knochendichte, Stimmung und Libido. Östrogendominanz wenn Progesteron relativ zu niedrig.',symptoms:['PMS','Stimmungsschwankungen','Regelschmerzen','Brustspannen','Hitzewallungen'],cofaktoren:[{name:'Vitamin B6',why:'Fördert Progesteron-Synthese'},{name:'Magnesium',why:'Aktiviert COMT für Östrogen-Entgiftung'}]},
  {slug:'progesteron',name:'Progesteron',aliases:['progesteron','progesterone','gelbkörperhormon'],description:'Gegenhormon zu Östrogen. Beruhigt, fördert Schlaf (via GABA-A), schützt Gebärmutter. Bei Mangel: PMS, Schlafstörung, Ängstlichkeit.',symptoms:['PMS','Schlafstörung','Angst','Stimmungsschwankungen','Zyklusstörungen'],cofaktoren:[{name:'Vitamin B6',why:'Progesteron-Synthese'},{name:'Zink',why:'Luteinisierendes Hormon (LH) – Progesteron-Stimulus'}]},
  {slug:'tsh',name:'TSH (Thyreoidea-stimulierendes Hormon)',aliases:['tsh','thyreoidea','schilddrüse','schilddrüsenhormon'],description:'Hypophysenhormon das Schilddrüse steuert. TSH erhöht = Unterfunktion. TSH erniedrigt = Überfunktion. Goldstandard-Screening für Schilddrüsenstatus.',symptoms:['Erschöpfung','Gewichtszunahme','Frieren','Haarausfall','Verstopfung','Depressive Stimmung'],cofaktoren:[{name:'Jod',why:'Baustein von T3 und T4'},{name:'Selen',why:'Dejodase T4→T3'},{name:'Zink',why:'T3-Rezeptor-Cofaktor'}]},
  // ── VITAMINE ────────────────────────────────────────────────────────────────
  {slug:'vitamin-d3',name:'Vitamin D3 (25-OH-Cholecalciferol)',aliases:['vitamin d','d3','25-oh-d','cholecalciferol'],description:'Prohormon das über 2000 Gene reguliert: Immunsystem, Knochen, Muskel, Nervensystem. 80% der Deutschen mangelhaft versorgt (< 30 ng/ml).',symptoms:['Erschöpfung','Infektanfälligkeit','Knochenschmerzen','Depression','Muskelkrämpfe','Haarausfall'],cofaktoren:[{name:'Vitamin K2',why:'Lenkt Calcium in Knochen statt Arterien'},{name:'Magnesium',why:'Cofaktor aller Vitamin-D-aktivierenden Enzyme'}]},
  {slug:'vitamin-b12',name:'Vitamin B12 (Cobalamin)',aliases:['vitamin b12','b12','cobalamin','methylcobalamin'],description:'Essenziell für Nervensystem, DNA-Synthese und Methylierungszyklus. Mangel schleicht über Jahre ein – häufig bei Veganern, Metformin- und PPI-Nutzern.',symptoms:['Erschöpfung','Kribbeln/Taubheit','Brain Fog','Vergesslichkeit','Anämie'],cofaktoren:[{name:'Folsäure',why:'B12 + Folat arbeiten im Methylierungszyklus zusammen'},{name:'Intrinsic Factor',why:'Magenprotein für B12-Absorption'}]},
  {slug:'folsaeure',name:'Folsäure (Vitamin B9)',aliases:['folsäure','folat','b9','mthfr','methylfolat'],description:'Essenziell für Zellteilung, DNA-Synthese und Methylierungszyklus. MTHFR-Mutation (30% der Population) reduziert Folat-Aktivierung auf aktives 5-MTHF.',symptoms:['Anämie','Erhöhtes Homocystein','Konzentrationsprobleme','Depressive Stimmung','Schwangerschaftskomplikationen'],cofaktoren:[{name:'Vitamin B12',why:'B12 + Folat im Methylierungszyklus'},{name:'Vitamin B6',why:'Homocystein-Abbau-Trias'}]},
  {slug:'vitamin-b6',name:'Vitamin B6 (Pyridoxin / P5P)',aliases:['vitamin b6','b6','pyridoxin','p5p','pyridoxal-5-phosphat'],description:'Cofaktor von 160+ Enzymen: Neurotransmitter-Synthese, Hormonstoffwechsel, Immunfunktion und Methylierung. Häufig bei Frauen mit Pille insuffizient.',symptoms:['Reizbarkeit','Schlafstörungen','PMS','Periphere Neuropathie','Depressive Stimmung'],cofaktoren:[{name:'Magnesium',why:'Synergistisch für Nervensystem'},{name:'Riboflavin (B2)',why:'Aktiviert B6 zur aktiven Form P5P'}]},
  {slug:'vitamin-e',name:'Vitamin E (Tocopherol)',aliases:['vitamin e','tocopherol','alpha-tocopherol'],description:'Wichtigstes fettlösliches Antioxidans. Schützt Zellmembranen, Omega-3-Fettsäuren und LDL vor Oxidation. Synergistisch mit Selen.',symptoms:['Muskelschwäche','Nervenschäden','Immunschwäche','Sehstörungen','Erschöpfung'],cofaktoren:[{name:'Selen',why:'GPX und Vitamin E schützen synergistisch vor Lipidperoxidation'},{name:'Vitamin C',why:'Regeneriert oxidiertes Vitamin E'}]},
  {slug:'coq10',name:'Coenzym Q10 (Ubiquinol)',aliases:['coq10','q10','ubiquinol','ubiquinon'],description:'Elektronencarrier in der mitochondrialen Atmungskette. Ohne CoQ10 kein ATP. Statine blockieren körpereigene CoQ10-Synthese – daher Pflicht-Check bei Statineinnahme.',symptoms:['Erschöpfung','Muskelschwäche','Herzprobleme','Brain Fog','Muskelschmerzen unter Statinen'],cofaktoren:[{name:'Selen',why:'Selenoprotein Q ist CoQ10-Cofaktor'},{name:'Vitamin B6',why:'CoQ10-Biosynthese'}]},
  {slug:'vitamin-c',name:'Vitamin C (Ascorbinsäure)',aliases:['vitamin c','ascorbinsäure','ascorbat'],description:'Wasserlösliches Antioxidans. Essenziell für Kollagensynthese, Eisenresorption, Immunfunktion und Nebennierenfunktion (höchste Konzentration im Nebennierenmark).',symptoms:['Wundheilungsstörung','Häufige Infekte','Erschöpfung','Zahnfleischbluten','Blutergüsse'],cofaktoren:[{name:'Bioflavonoide',why:'Synergistisch mit Vitamin C'},{name:'Eisen',why:'Vitamin C steigert Fe-Resorption um 300%'}]},
  // ── MINERALSTOFFE ───────────────────────────────────────────────────────────
  {slug:'magnesium',name:'Magnesium (intrazellulär)',aliases:['magnesium','mg','magnesium malat'],description:'Cofaktor von über 300 Enzymen. Essenziell für ATP-Synthese, Muskelentspannung, Schlaf und Nervenfunktion. Intrazelluläre Messung im Vollblut deutlich aussagekräftiger als Serum.',symptoms:['Muskelkrämpfe','Schlafprobleme','Herzrasen','Kopfschmerzen','Erschöpfung','Innere Unruhe'],cofaktoren:[{name:'Vitamin D',why:'Cofaktor aller Vitamin-D-Enzyme'},{name:'Vitamin B6',why:'Synergistisch: fördert Mg-Eintritt in Zelle'}]},
  {slug:'zink',name:'Zink (intrazellulär)',aliases:['zink','zinc','zn'],description:'Cofaktor von 300+ Enzymen. Kritisch für Immunsystem, Wundheilung, Hormonproduktion und DNA-Synthese. Intrazelluläre Messung im Vollblut unverzichtbar.',symptoms:['Häufige Infekte','Haarausfall','Wundheilungsstörung','Akne','Geschmacksverlust'],cofaktoren:[{name:'Kupfer',why:'Kupfer-Zink-Ratio ist Entzündungsmarker'},{name:'Vitamin A',why:'Zink aktiviert Retinol-Bindungsprotein'}]},
  {slug:'selen',name:'Selen (intrazellulär)',aliases:['selen','selenium','se','selenomethionin'],description:'Cofaktor von 25 Selenoproteinen: Glutathion-Peroxidase, Thioredoxin-Reduktase und Dejodasen (Schilddrüse T4→T3). Selenböden in Deutschland besonders arm.',symptoms:['Schilddrüsenprobleme','Erschöpfung','Immunschwäche','Muskelschmerzen','Haarausfall'],cofaktoren:[{name:'Vitamin E',why:'Synergistischer antioxidativer Schutz'},{name:'Jod',why:'Selen-Dejodase aktiviert T4→T3'}]},
  {slug:'eisen',name:'Eisen (intrazellulär)',aliases:['eisen','iron','fe','serumeisen'],description:'Cofaktor der Tyrosinhydroxylase (Dopamin) und essenziell für Sauerstofftransport (Hämoglobin). Intrazelluläre Messung zeigt Versorgung der Zellen, nicht nur Transportpool.',symptoms:['Erschöpfung','Blässe','Restless Legs','Konzentrationsprobleme','Kurzatmigkeit'],cofaktoren:[{name:'Vitamin C',why:'Steigert Fe-Resorption um 300%'},{name:'Kupfer',why:'Ceruloplasmin transportiert Eisen'}]},
  {slug:'ferritin',name:'Ferritin',aliases:['ferritin','eisenspeicher','eisenmangel'],description:'Eisenspeicherprotein – zeigt Langzeit-Versorgung. Ferritin < 30 ng/ml: funktioneller Eisenmangel trotz normalem Serumeisen möglich. Ferritin ist auch Akute-Phase-Protein (bei Entzündung erhöht).',symptoms:['Haarausfall','Erschöpfung','Konzentrationsprobleme','Blässe','Restless Legs'],cofaktoren:[{name:'Vitamin C',why:'Fördert Ferritin-Einlagerung'},{name:'Vitamin B12 + Folsäure',why:'Blutbildung gemeinsam mit Eisen'}]},
  {slug:'kupfer',name:'Kupfer (intrazellulär)',aliases:['kupfer','copper','cu','ceruloplasmin'],description:'Cofaktor für Bindegewebe (Lysyloxidase), Eisentransport (Ceruloplasmin), Mitochondrien (Cytochrom-c-Oxidase) und Dopamin-Synthese (DBH). Kupfer-Zink-Ratio = Entzündungsmarker.',symptoms:['Anämie','Erschöpfung','Osteoporose','Pigmentierungsstörungen','Nervenschäden'],cofaktoren:[{name:'Zink',why:'Kupfer-Zink-Ratio'},{name:'Vitamin C',why:'Kupfer-abhängige Enzyme'}]},
  {slug:'calcium',name:'Calcium (intrazellulär)',aliases:['calcium','kalzium','ca'],description:'Häufigster Mineralstoff. Essenziell für Knochen, Muskelkontraktion, Nervensignale und Blutgerinnung. Intrazelluläres Kalzium-Signal regelt Zellfunktion.',symptoms:['Muskelkrämpfe','Kribbeln','Herzrhythmusstörungen','Schlafstörungen','Knochenschwäche'],cofaktoren:[{name:'Vitamin D',why:'Reguliert Calcium-Resorption im Darm'},{name:'Vitamin K2',why:'Lenkt Calcium in Knochen (MGP-Protein)'}]},
  {slug:'natrium',name:'Natrium (intrazellulär)',aliases:['natrium','sodium','na'],description:'Hauptkation im Extrazellulärraum. Reguliert Flüssigkeitshaushalt, Blutdruck und Nervenimpulse. Na/K-ATPase ist der wichtigste Energieverbraucher der Zelle.',symptoms:['Bluthochdruck','Ödeme','Schwindel','Muskelschwäche'],cofaktoren:[{name:'Magnesium',why:'Reguliert Na/K-ATPase'}]},
  {slug:'kalium',name:'Kalium (intrazellulär)',aliases:['kalium','potassium','k'],description:'Hauptkation im Intrazellulärraum. Essenziell für Herzrhythmus, Muskelkontraktion und Nervenimpulse. Kalium-Mangel durch Stress, Diuretika oder Erbrechen.',symptoms:['Herzrhythmusstörungen','Muskelkrämpfe','Schwäche','Obstipation','Erschöpfung'],cofaktoren:[{name:'Magnesium',why:'Ohne Magnesium kein Kalium in Zelle'}]},
  {slug:'jod',name:'Jod (Urin)',aliases:['jod','iod','iodine','jodmangel'],description:'Einziger Baustein der Schilddrüsenhormone T3 und T4. Deutschland ist klassisches Jodmangelgebiet. Jodmangel = weltweit häufigste vermeidbare Ursache für geistige Entwicklungsstörungen.',symptoms:['Schilddrüsenunterfunktion','Erschöpfung','Gewichtszunahme','Struma','Kognitive Verlangsamung'],cofaktoren:[{name:'Selen',why:'Dejodase (T4→T3) ist selenabhängig'},{name:'Vitamin D',why:'Moduliert Jod-Aufnahme in Schilddrüsenzellen'}]},
  // ── FETTSÄUREN ──────────────────────────────────────────────────────────────
  {slug:'epa',name:'EPA (Eicosapentaensäure)',aliases:['epa','eicosapentaensäure','omega-3','fischöl'],description:'Omega-3-Fettsäure mit stärkster entzündungshemmender Wirkung – Vorläufer von Resolvinen und Protektinen. EPA/AA-Quotient ist wichtigster Entzündungsmarker.',symptoms:['Entzündungen','Herzerkrankung','Depression','Gelenkschmerzen'],cofaktoren:[{name:'Vitamin E',why:'Schützt EPA vor Oxidation'},{name:'Magnesium',why:'Synergistisch kardioprotetkiv'}]},
  {slug:'dha',name:'DHA (Docosahexaensäure)',aliases:['dha','docosahexaensäure','omega-3'],description:'Omega-3-Fettsäure – macht 40% aller Hirnfettsäuren aus. Essenziell für Neuronenmembranfluidität, Synapsenbildung und Sehfähigkeit (Retina 60% DHA).',symptoms:['Brain Fog','Depression','Sehstörungen','ADHS','Demenz'],cofaktoren:[{name:'Vitamin E',why:'DHA-Oxidationsschutz'}]},
  {slug:'ala',name:'ALA (Alpha-Linolensäure)',aliases:['ala','alpha-linolensäure','pflanzliches omega-3'],description:'Pflanzliches Omega-3 (Leinöl, Walnüsse). Konversion zu EPA/DHA nur ~5-15% effizient. Kein Ersatz für marine Omega-3, aber wichtig für Membranfunktion.',symptoms:['Entzündungen','Trockene Haut'],cofaktoren:[{name:'Zink',why:'Desaturase-Cofaktor'}]},
  {slug:'linolsaeure',name:'Linolsäure (Omega-6)',aliases:['linolsäure','omega-6','la'],description:'Häufigste Omega-6-Fettsäure in westlicher Ernährung. Omega-6/Omega-3-Quotient > 10:1 fördert chronische Entzündung. Sollte < 3:1 sein.',symptoms:['Chronische Entzündung','Herzerkrankung'],cofaktoren:[{name:'EPA/DHA',why:'Gegenspieler im Arachidonsäure-Weg'}]},
  {slug:'arachidonsaeure',name:'Arachidonsäure (AA)',aliases:['arachidonsäure','aa','omega-6'],description:'Aus Linolsäure synthetisierte Omega-6-Fettsäure – Vorläufer entzündungsfördernder Eikosanoide (PGE2, Leukotriene). EPA/AA-Quotient < 0.5 = erhöhtes Entzündungsrisiko.',symptoms:['Entzündungsschmerzen','Arthritis','Herzerkrankung'],cofaktoren:[{name:'EPA',why:'Kompetitiver Inhibitor der AA-Eikosanoid-Synthese'}]},
  {slug:'omega6-3-quotient',name:'Omega-6/3-Quotient',aliases:['omega-6/3','omega quotient','entzündungsquotient'],description:'Verhältnis Omega-6 zu Omega-3 in Erythrozyten. Idealwert < 3:1. Westliche Ernährung: 15-20:1. Wichtigster systemischer Entzündungsmarker über Fettsäure-Analytik.',symptoms:['Chronische Entzündung','Herzerkrankung','Depression','Gelenkschmerzen'],cofaktoren:[{name:'EPA+DHA',why:'Direktes Senken des Quotienten'}]},
  {slug:'epa-aa-quotient',name:'EPA/AA-Quotient',aliases:['epa/aa','entzündungsindex'],description:'Verhältnis von entzündungshemmendem EPA zu entzündungsfördernder Arachidonsäure. Optimalwert > 0.5. Unter 0.25 = deutlich erhöhtes Herzinfarktrisiko.',symptoms:['Herzerkrankung','Chronische Entzündung','Atherosklerose'],cofaktoren:[{name:'EPA/DHA-Supplementation',why:'Direkter Quotient-Verbesserer'}]},
  {slug:'transfettsaeuren',name:'Transfettsäuren',aliases:['transfettsäuren','transfette','elaidinsäure'],description:'Industriell gehärtete Fettsäuren – erhöhen LDL, senken HDL, fördern Entzündung massiv. Jede 2%-Kalorienerhöhung durch Transfette steigert Herzinfarktrisiko um 23%.',symptoms:['Herzerkrankung','Erhöhtes LDL','Entzündungen'],cofaktoren:[]},
  // ── ENTZÜNDUNGS- & HERZMARKER ───────────────────────────────────────────────
  {slug:'hscrp',name:'hsCRP (hochsensitives C-reaktives Protein)',aliases:['hscrp','hs-crp','crp','entzündung','crp-wert'],description:'Sensitivster Marker für systemische Entzündung. hsCRP > 1 mg/L = erhöhtes Herzinfarktrisiko. hsCRP > 3 = hohes Risiko. Wichtigster kardiovaskulärer Prädiktor neben LDL.',symptoms:['Chronische Erschöpfung','Gelenkschmerzen','Brain Fog','Herzerkrankung','Häufige Infekte'],cofaktoren:[{name:'Omega-3 (EPA/DHA)',why:'Senkt hsCRP durch Resolvine'},{name:'Vitamin D',why:'Hemmt NF-κB'},{name:'Curcumin',why:'Potenter NF-κB-Hemmer'}]},
  {slug:'gesamt-cholesterin',name:'Gesamtcholesterin',aliases:['cholesterin','gesamt-cholesterin','gesamtcholesterin'],description:'Summe aller Cholesterin-Fraktionen. Allein wenig aussagekräftig – entscheidend ist LDL/HDL-Ratio und ob LDL oxidiert ist.',symptoms:['Herzerkrankung','Atherosklerose'],cofaktoren:[{name:'Omega-3',why:'Senkt Triglyzeride'},{name:'Coenzym Q10',why:'Schützt LDL vor Oxidation'}]},
  {slug:'hdl-cholesterin',name:'HDL-Cholesterin',aliases:['hdl','hdl-cholesterin','gutes cholesterin'],description:'"Gutes" Cholesterin – transportiert Cholesterin zurück zur Leber (reverser Cholesterintransport). HDL < 40 mg/dl (Männer) / < 50 mg/dl (Frauen) = Risikofaktor.',symptoms:['Herzerkrankung','Atherosklerose','Metabolisches Syndrom'],cofaktoren:[{name:'Omega-3',why:'Erhöht HDL'},{name:'Bewegung',why:'Stärkster HDL-Erhöher'}]},
  {slug:'ldl-cholesterin',name:'LDL-Cholesterin',aliases:['ldl','ldl-cholesterin','schlechtes cholesterin'],description:'"Schlechtes" Cholesterin – nur wenn oxidiert gefährlich. Oxidiertes LDL (ox-LDL) triggert Plaquebildung. LDL allein ohne Oxidationsmarker unvollständig bewertet.',symptoms:['Herzerkrankung','Atherosklerose','Xanthome'],cofaktoren:[{name:'Coenzym Q10',why:'Schützt LDL vor Oxidation'},{name:'Vitamin E',why:'Antioxidativer LDL-Schutz'}]},
  {slug:'triglyzeride',name:'Triglyzeride',aliases:['triglyzeride','triglyceride','neutralfette'],description:'Blutfette aus Kohlenhydrat-Überschuss und Alkohol. Triglyzeride > 150 mg/dl = Risikofaktor für Herzerkrankung und Pankreatitis. Zeigen Insulinresistenz an.',symptoms:['Herzerkrankung','Pankreatitis','Metabolisches Syndrom','Fettleber'],cofaktoren:[{name:'Omega-3 EPA/DHA',why:'Senkt Triglyzeride um 20-30%'}]},
  // ── ORGANISCHE SÄUREN ───────────────────────────────────────────────────────
  {slug:'pyruvat',name:'Pyruvat',aliases:['pyruvat','pyruvate','pyruvic acid'],description:'Endprodukt der Glykolyse – Eintrittspunkt in den Citratzyklus. Erhöht bei mitochondrialer Dysfunktion oder Thiamin(B1)-Mangel.',symptoms:['Erschöpfung','Muskelschmerzen','Brain Fog'],cofaktoren:[{name:'Vitamin B1 (Thiamin)',why:'Cofaktor der Pyruvat-Dehydrogenase'}]},
  {slug:'laktat',name:'Laktat',aliases:['laktat','lactat','milchsäure'],description:'Anaerobes Stoffwechselprodukt. Laktat/Pyruvat-Ratio > 20 zeigt mitochondriale Dysfunktion an. Erhöht bei intensivem Sport, Hypoxie oder Mitochondrienpathologie.',symptoms:['Muskelschwäche','Erschöpfung','Muskelkrämpfe nach Sport'],cofaktoren:[{name:'Coenzym Q10',why:'Mitochondriale Atmungskette'}]},
  {slug:'zitrat',name:'Zitrat (Zitronensäure)',aliases:['zitrat','citrat','citrate','zitratzyklus'],description:'Erstes Intermediat des Zitratzyklus (Krebszyklus). Zitrat-Mangel zeigt blockierten Energiestoffwechsel an. Erhöht bei Statineinnahme.',symptoms:['Erschöpfung','Muskelschmerzen','Brain Fog'],cofaktoren:[{name:'Magnesium',why:'Aconitase-Cofaktor im Zitratzyklus'}]},
  {slug:'alpha-ketoglutarat',name:'Alpha-Ketoglutarat (2-Oxoglutarat)',aliases:['alpha-ketoglutarat','2-oxoglutarat','akg'],description:'Zentrales Intermediat des Zitratzyklus – Knotenpunkt für Aminosäure- und Energiestoffwechsel. AKG ist auch Cofaktor epigenetischer Demetylierungsenzyme (TET).',symptoms:['Erschöpfung','Erschöpfung nach Essen'],cofaktoren:[{name:'Vitamin B2 (Riboflavin)',why:'Isocitrat-Dehydrogenase'}]},
  {slug:'fumarat',name:'Fumarat',aliases:['fumarat','fumarat','fumaric acid'],description:'Zitratzyklus-Intermediat zwischen Succinat und Malat. Erhöhtes Fumarat kann auf Succinat-Dehydrogenase-Störung hinweisen.',symptoms:['Erschöpfung','Mitochondriale Dysfunktion'],cofaktoren:[{name:'Vitamin B2',why:'Succinat-Dehydrogenase (FAD)'}]},
  {slug:'malat',name:'Malat (Äpfelsäure)',aliases:['malat','malate','äpfelsäure'],description:'Wichtiges Zitratzyklus-Intermediat. Malat kann Mitochondrien direkt Energie liefern (Malat-Aspartat-Shuttle). Malat-Supplementation hilft bei Fibromyalgie.',symptoms:['Erschöpfung','Fibromyalgie','Muskelschmerzen'],cofaktoren:[{name:'Magnesium',why:'Malat-Dehydrogenase'}]},
  {slug:'succinat',name:'Succinat (Bernsteinsäure)',aliases:['succinat','succinate','bernsteinsäure'],description:'Zitratzyklus-Intermediat, Substrat der Succinat-Dehydrogenase (Komplex II der Atmungskette). Erhöht bei mitochondrialer Dysfunktion und Entzündung.',symptoms:['Erschöpfung','Entzündungen','Mitochondriale Dysfunktion'],cofaktoren:[{name:'Coenzym Q10',why:'Komplex II–III Elektronen-Transfer'}]},
  {slug:'3-hydroxybutyrat',name:'3-Hydroxybutyrat (Beta-Hydroxybutyrat)',aliases:['3-hydroxybutyrat','bhb','beta-hydroxybutyrat','ketone'],description:'Hauptketon-Körper. Erhöht bei Ketose (Fasten, ketogene Diät) oder Ketoazidose (Diabetes). Zeigt Fettverbrennung an – kann als Marker für metabolische Flexibilität genutzt werden.',symptoms:['Blutzuckerschwankungen','Erschöpfung','Diabetes'],cofaktoren:[]},
  {slug:'methylmalonsaeure',name:'Methylmalonsäure (MMA)',aliases:['methylmalonsäure','mma','b12-marker'],description:'Empfindlichster Marker für funktionellen Vitamin-B12-Mangel – steigt schon bevor B12-Serumspiegel sinkt. Zeigt mitochondriale Propionat-Verwertungsstörung an.',symptoms:['Kribbeln','Brain Fog','Erschöpfung','Nervenschäden'],cofaktoren:[{name:'Vitamin B12 (Adenosylcobalamin)',why:'Cofaktor der Methylmalonyl-CoA-Mutase'}]},
  {slug:'8-ohdg',name:'8-OHdG (8-Hydroxy-2-Desoxyguanosin)',aliases:['8-ohdg','8-hydroxydesoxyguanosin','dna-oxidation','zellstress'],description:'Direkter Marker für oxidativen DNA-Schaden – zeigt Tempo des Alterns auf Zellebene. Erhöhte Werte zeigen Krebsrisiko, Mitochondrien-Dysfunktion und beschleunigtes Altern.',symptoms:['Beschleunigtes Altern','Kognitive Abnahme','Erschöpfung','Entzündungsneigung'],cofaktoren:[{name:'CoQ10',why:'Schützt mitochondriale DNA'},{name:'Alpha-Liponsäure',why:'Universalantioxidans'},{name:'NAC',why:'Glutathion-Erhöhung'}]},
  {slug:'kynurensaeure',name:'Kynurensäure',aliases:['kynurensäure','kynurenic acid'],description:'Abbauprodukt des Kynurenin-Wegs – NMDA-Rezeptor-Antagonist. Bei Überproduktion: kognitive Verlangsamung und Psychose-Risiko.',symptoms:['Brain Fog','Kognitive Verlangsamung','Depressive Stimmung'],cofaktoren:[{name:'Vitamin B6',why:'KAT-Enzym-Cofaktor'}]},
  {slug:'quinolinsaeure',name:'Quinolinsäure (Chinolinsäure)',aliases:['quinolinsäure','chinolinsäure','quinolinic acid'],description:'Neurotoxisches Abbauprodukt des Kynurenin-Wegs – NMDA-Agonist. Bei Entzündung erhöht → Neuroinflammation, Depression, Neurodegenerations-Marker.',symptoms:['Neuroinflammation','Depression','Brain Fog','Demenz'],cofaktoren:[{name:'NAC',why:'Hemmt Quinolinsäure-Produktion'},{name:'Magnesium',why:'Puffert NMDA-Überstimulation'}]},
  {slug:'4-hydroxynitrophenyl-essigsaeure',name:'4-Hydroxynitrophenyl-Essigsäure (RNS-Marker)',aliases:['4-hydroxynitrophenyl','rns','nitrosativer stress','nitrostress-marker'],description:'Spezifischer Marker für nitrosativen Stress durch reaktive Stickstoffspezies (RNS). Erhöhte Werte bei Mitochondrienschaden, chronischer Entzündung und NO-Dysregulation.',symptoms:['Erschöpfung','Mitochondriale Dysfunktion','Chronische Entzündung'],cofaktoren:[{name:'Arginin',why:'NO-Synthase-Substrat – Balance nötig'}]},
  {slug:'kreatinin',name:'Kreatinin (Urin-Referenzwert)',aliases:['kreatinin','creatinine','kreatinin urin'],description:'Referenzwert zur Normalisierung von Urin-Biomarkern. Zeigt Urin-Konzentration an. Auch Nierenfunktionsmarker (Serum-Kreatinin).',symptoms:['Nierenproblem'],cofaktoren:[]},
  // ── DARMMARKER ──────────────────────────────────────────────────────────────
  {slug:'calprotectin',name:'Calprotectin (Stuhl)',aliases:['calprotectin','calprotektin','darmwandentzündung'],description:'Sensitivster Marker für mukosale Darmentzündung. Differenziert entzündliche Darmerkrankung (CED) von funktionellem Reizdarm. Calprotectin > 50 µg/g = aktive Entzündung.',symptoms:['Blut im Stuhl','Chronischer Durchfall','Bauchschmerzen','Gewichtsverlust','Gelenkentzündungen'],cofaktoren:[{name:'Curcumin',why:'Entzündungshemmend bei CED'},{name:'Omega-3',why:'Senkt Calprotectin in Studien'}]},
  {slug:'zonulin',name:'Zonulin (Stuhl)',aliases:['zonulin','leaky gut','darmpermeabilität','tight junctions'],description:'Regulator der intestinalen Tight Junctions. Erhöhtes Zonulin = erhöhte Darmpermeabilität (Leaky Gut). Gluten und Lipopolysaccharide sind stärkste Zonulin-Trigger.',symptoms:['Nahrungsmittelunverträglichkeiten','Blähungen','Brain Fog','Autoimmunerkrankung','Hautprobleme'],cofaktoren:[{name:'L-Glutamin',why:'Stärkt Tight Junctions'},{name:'Vitamin D',why:'Reguliert Tight-Junction-Proteine'}]},
  {slug:'sekretorisches-iga',name:'Sekretorisches IgA (sIgA)',aliases:['sekretorisches iga','siga','darmimmunität'],description:'Wichtigstes Immunglobulin der Darmschleimhaut. sIgA schützt vor Pathogenen und reguliert Mikrobiom. Niedriger sIgA = geschwächte Darmimmunabwehr.',symptoms:['Häufige Darminfekte','Diarrhö','Nahrungsmittelreaktion','Chronische Erschöpfung'],cofaktoren:[{name:'Vitamin A',why:'Essenziell für sIgA-Produktion'},{name:'Probiotika',why:'Stimulieren sIgA-Sekretion'}]},
  {slug:'pankreas-elastase',name:'Pankreatische Elastase-1 (PE-1)',aliases:['elastase','pankreas-elastase','pe-1','exokrine pankreasinsuffizienz'],description:'Marker für exokrine Pankreasfunktion. Elastase < 200 µg/g Stuhl = exokrine Pankreasinsuffizienz (EPI) → Fettmalabsorption, Blähungen, Durchfall.',symptoms:['Blähungen','Fettiger Stuhl','Durchfall','Gewichtsverlust','Bauchschmerzen'],cofaktoren:[{name:'Verdauungsenzyme',why:'Direkte Substitution bei EPI'}]},
  {slug:'histamin-stuhl',name:'Histamin (Stuhl)',aliases:['histamin stuhl','intestinales histamin','darm-histamin'],description:'Histamin im Stuhl wird von Darmbakterien produziert. Erhöhte Werte bei Dysbiose und DAO-Mangel. Zusammen mit DAO-Enzym der vollständige Histaminintoleranz-Check.',symptoms:['Histaminunverträglichkeit','Kopfschmerzen nach Essen','Flush','Herzrasen','Blähungen'],cofaktoren:[{name:'DAO-Enzym',why:'Abbau von intestinalem Histamin'},{name:'Vitamin B6',why:'DAO-Cofaktor'}]},
  {slug:'dao-enzym',name:'DAO-Enzym (Diaminoxidase)',aliases:['dao','diaminoxidase','histaminabbau','dao-enzym'],description:'Hauptenzym zum Histaminabbau im Darm. DAO-Mangel → Histamin akkumuliert nach histaminreicher Mahlzeit. DAO-Aktivität < 3 HDU/ml = Histaminintoleranz.',symptoms:['Histaminunverträglichkeit','Kopfschmerzen nach Essen','Juckreiz','Herzrasen','Flush'],cofaktoren:[{name:'Vitamin B6 (P5P)',why:'Cofaktor der DAO'},{name:'Kupfer',why:'Cofaktor der DAO'},{name:'Vitamin C',why:'Stabilisiert DAO'}]},
  {slug:'beta-glucuronidase',name:'ß-Glucuronidase',aliases:['beta-glucuronidase','glucuronidase','östrogen-recycling'],description:'Bakterielles Enzym das konjugiertes Östrogen im Darm reaktiviert (dekonjugiert) → enterohepatische Rezirkulation → Östrogendominanz. Erhöhte Aktivität bei Dysbiose.',symptoms:['PMS','Östrogendominanz','Brustspannen','Akne','Hormondysbalance'],cofaktoren:[{name:'Calcium-D-Glucarat',why:'Hemmt ß-Glucuronidase direkt'},{name:'DIM',why:'Schützende Östrogenmetabolite'}]},
  {slug:'gallensaeuren',name:'Gallensäuren (Stuhl)',aliases:['gallensäuren','bile acids','gallensäure-metabolismus'],description:'Gallensäuren im Stuhl zeigen hepatobiliäre Funktion und Darm-Mikrobiom-Zusammensetzung. Primäre Gallensäuren werden durch Bakterien in sekundäre umgewandelt.',symptoms:['Fettiger Stuhl','Blähungen','Durchfall','Bauchschmerzen','Leberprobleme'],cofaktoren:[{name:'Taurin',why:'Gallensäure-Konjugation'}]},
  {slug:'h2-atemgas',name:'Wasserstoff H₂ (Atemgas)',aliases:['wasserstoff','h2','atemtest','sibo-wasserstoff'],description:'H₂-Produktion durch bakterielle Fermentation von Kohlenhydraten im Dünndarm. H₂-Anstieg > 20 ppm nach Lactulose = Wasserstoff-SIBO. Messung über 90 Minuten.',symptoms:['Blähungen','Durchfall','Bauchschmerzen','Reizdarm'],cofaktoren:[{name:'Probiotika (L. reuteri)',why:'Reduziert SIBO-Keimbesiedlung'}]},
  {slug:'ch4-atemgas',name:'Methan CH₄ (Atemgas)',aliases:['methan','ch4','methan-sibo','archaeen'],description:'CH₄-Produktion durch Methanogen-Archaeen im Dickdarm. Methan-SIBO verlangsamt Darmtransit → Verstopfung. CH₄ > 10 ppm = Methan-SIBO.',symptoms:['Verstopfung','Blähungen','Reizdarm','Bauchschmerzen'],cofaktoren:[{name:'Probiotika (L. reuteri)',why:'Reduziert Methanogen-Archaeen'}]},
  {slug:'laktose-h2',name:'H₂ nach Laktose-Belastung',aliases:['laktose atemtest','laktoseintoleranz','milchzucker'],description:'H₂-Anstieg > 20 ppm nach Laktose-Einnahme = Laktoseintoleranz (Laktasemangel). Unverdaute Laktose wird im Dickdarm fermentiert → Blähungen, Krämpfe, Durchfall.',symptoms:['Blähungen nach Milchprodukten','Bauchkrämpfe','Durchfall','Übelkeit'],cofaktoren:[{name:'Laktase-Enzyme',why:'Direkte Enzymsubstitution'},{name:'Probiotika (L. acidophilus)',why:'Produzieren Laktase'}]},
  {slug:'fruktose-h2',name:'H₂ nach Fruktose-Belastung',aliases:['fruktose atemtest','fruktoseintoleranz','fruchtzucker'],description:'H₂-Anstieg nach Fruktose = Fruktose-Malabsorption durch GLUT5-Transporter-Mangel. Häufig bei FODMAP-Unverträglichkeit und Reizdarm.',symptoms:['Blähungen nach Obst','Bauchkrämpfe','Durchfall','Reizdarm'],cofaktoren:[{name:'Low-FODMAP-Ernährung',why:'Direkteste Therapie'}]},
  {slug:'anti-gliadin-aga',name:'Anti-Gliadin-Antikörper (AGA)',aliases:['anti-gliadin','aga','gliadin-antikörper','gluten'],description:'Antikörper gegen Gliadin-Peptide aus Weizen. Marker für Glutensensitivität und nicht-zöliakische Weizenreaktivität. Negativer Prädiktor für Darmschleimhautstatus.',symptoms:['Blähungen','Bauchschmerzen','Erschöpfung','Brain Fog','Hautprobleme'],cofaktoren:[{name:'Glutenfreie Diät',why:'Einzige wirksame Therapie'}]},
  {slug:'anti-tg2',name:'Anti-Transglutaminase-2-Antikörper (anti-TG2)',aliases:['anti-tg2','tg2','transglutaminase','zöliakie'],description:'Hochspezifischer Marker für Zöliakie (Autoimmunerkrankung). Positiver anti-TG2 + klinische Symptome = dringende Dünndarmbiopsie-Indikation. Sensitivität 95%, Spezifität 97%.',symptoms:['Durchfall','Blähungen','Gewichtsverlust','Anämie','Wachstumsstörung bei Kindern'],cofaktoren:[{name:'Strikt glutenfreie Diät',why:'Einzige Therapie bei Zöliakie'}]},
  {slug:'igg-lebensmittel',name:'IgG-Antikörper gegen Lebensmittel (270)',aliases:['igg','igg-antikörper','nahrungsmittelunverträglichkeit','food intolerance'],description:'IgG-Antikörper entstehen bei verzögerter Immunreaktion auf Lebensmittel (6-72h nach Konsum). Bei Leaky Gut systematisch erhöht. IgG Klasse 3-4 = klinisch relevant.',symptoms:['Nahrungsmittelunverträglichkeiten','Blähungen','Hautprobleme','Brain Fog','Migräne'],cofaktoren:[{name:'L-Glutamin',why:'Repariert Darmbarriere'},{name:'Probiotika',why:'Reduzieren Darmpermeabilität'}]},
  // ── MIKROBIOM ───────────────────────────────────────────────────────────────
  {slug:'lactobacillus',name:'Lactobacillus spp.',aliases:['lactobacillus','milchsäurebakterien','l. acidophilus','l. reuteri'],description:'Wichtigste probiotische Bakteriengruppe – produzieren Milchsäure, senken pH, hemmen Pathogene und produzieren Laktase. Entscheidend für vaginale und intestinale Gesundheit.',symptoms:['Blähungen','Diarrhö','Vaginale Infekte','Laktoseintoleranz','Immunschwäche'],cofaktoren:[{name:'Präbiotika (Inulin, FOS)',why:'Selektives Wachstum von Lactobazillen'}]},
  {slug:'bifidobacterium',name:'Bifidobacterium spp.',aliases:['bifidobacterium','bifido','bifidum'],description:'Schlüsselgattung für Darmbarriere, Vitamin-B-Synthese und Immunmodulation. Bifidobacterium sinkt mit Alter und Antibiotikaeinnahme stark ab.',symptoms:['Blähungen','Verstopfung','Immunschwäche','Stimmungsschwankungen'],cofaktoren:[{name:'Präbiotika (GOS, FOS)',why:'Bifidogener Effekt'},{name:'Vitamin D',why:'Fördert Bifidobacterium-Wachstum'}]},
  {slug:'akkermansia',name:'Akkermansia muciniphila',aliases:['akkermansia','akkermansia muciniphila'],description:'Schleimhautbewohner mit schleimlösender Wirkung – paradoxerweise stärkt Akkermansia die Darmbarriere. Niedrige Werte korrelieren mit Übergewicht, Diabetes und metabolischem Syndrom.',symptoms:['Übergewicht','Insulinresistenz','Leaky Gut','Metabolisches Syndrom'],cofaktoren:[{name:'Polyphenole (Granatapfel)',why:'Selektives Akkermansia-Wachstum'},{name:'Cranberry',why:'Fördert Akkermansia'}]},
  {slug:'faecalibacterium',name:'Faecalibacterium prausnitzii',aliases:['faecalibacterium','f. prausnitzii','butyrat-produzent'],description:'Wichtigster Butyrat-Produzent und Entzündungshemmer im Dickdarm. Stark reduziert bei CED (Morbus Crohn, Colitis ulcerosa) und Depression. Gilt als "Wohlbefinden-Bakterium".',symptoms:['Chronische Darmentzündung','Colitis','Depression','Blähungen'],cofaktoren:[{name:'Resistente Stärke',why:'Selektiver Butyrat-Präbiotikum'}]},
  {slug:'candida',name:'Candida spp. (Stuhl)',aliases:['candida','pilze','hefen','candida albicans'],description:'Überwuchern bei Dysbiose, Antibiotikaeinnahme oder Zuckerreicher Ernährung. Candida produziert Acetaldehyd (Neurotoxin) und Ethanol im Darm → Brain Fog, Erschöpfung.',symptoms:['Brain Fog','Erschöpfung','Blähungen','Süßhunger','Vaginale Infekte','Zungenpilz'],cofaktoren:[{name:'Probiotika',why:'Kompetitive Verdrängung'},{name:'Zuckerreduzierte Ernährung',why:'Entzug der Candida-Nahrungsquelle'}]},
  {slug:'mikrobiom-diversitaet',name:'Mikrobiom-Diversität (Shannon-Index)',aliases:['mikrobiom','darmflora','diversität','shannon','alpha-diversität'],description:'Alpha-Diversität des Mikrobioms – je mehr verschiedene Spezies, desto resilienter das Mikrobiom. Niedrige Diversität korreliert mit Übergewicht, Entzündung und Depression.',symptoms:['Darmprobleme','Übergewicht','Depression','Immunschwäche','Reizdarm'],cofaktoren:[{name:'Fermentierte Lebensmittel',why:'Erhöhen Mikrobiom-Diversität'},{name:'Präbiotika',why:'Selektives Wachstum'}]},
  {slug:'dysbiose-index',name:'Dysbiose-Index',aliases:['dysbiose','dysbiose-index','darmungleichgewicht'],description:'Verhältnis protektiver zu pathogener Bakteriengruppen. Dysbiose = Übergewicht pathogener Keime. Marker für intestinales Ungleichgewicht als Ursache systemischer Symptome.',symptoms:['Blähungen','Reizdarm','Nahrungsmittelunverträglichkeiten','Immunschwäche','Brain Fog'],cofaktoren:[{name:'Probiotika',why:'Direktes Dysbiose-Korrektiv'}]},
  {slug:'lps-toxine',name:'Lipopolysaccharide (LPS / Endotoxine)',aliases:['lps','lipopolysaccharide','endotoxine','gram-negativ'],description:'Zellwandbestandteile gramnegativer Bakterien. Bei Leaky Gut gelangen LPS ins Blut → "Metabolische Endotoxämie" → systemische Entzündung, Insulinresistenz, Übergewicht.',symptoms:['Chronische Entzündung','Insulinresistenz','Brain Fog','Erschöpfung','Übergewicht'],cofaktoren:[{name:'Omega-3',why:'Reduziert LPS-induzierte Entzündung'},{name:'Vitamin D',why:'Hemmt LPS-TLR4-Signalweg'}]},
  // ── PARASITENMARKER ─────────────────────────────────────────────────────────
  {slug:'blastocystis-pcr',name:'Blastocystis hominis (PCR)',aliases:['blastocystis','blastocystis hominis'],description:'Häufigster intestinaler Protozoa weltweit – bei 15-30% der Reizdarm-Patienten. Pathogenität umstritten, aber bei symptomatischen Patienten oft therapiebedürftig.',symptoms:['Chronischer Durchfall','Blähungen','Bauchkrämpfe','Reizdarm','Erschöpfung'],cofaktoren:[{name:'Berberin',why:'Antiprotozoale Wirkung'},{name:'Probiotika',why:'Kompetitive Hemmung'}]},
  {slug:'giardia-pcr',name:'Giardia lamblia (PCR)',aliases:['giardia','giardiasis','lamblien'],description:'Häufigste parasitäre Darminfektion. Giardia zerstört Bürstensaum → Laktasemangel, Fettstühle, chronische Durchfälle. PCR deutlich sensitiver als mikroskopische Stuhluntersuchung.',symptoms:['Fettstühle','Durchfall','Bauchkrämpfe','Gewichtsverlust','Laktoseintoleranz'],cofaktoren:[{name:'Metronidazol/Tinidazol',why:'Therapie der Wahl'}]},
  {slug:'dientamoeba-pcr',name:'Dientamoeba fragilis (PCR)',aliases:['dientamoeba','dientamoeba fragilis'],description:'Intestinaler Parasit – häufig als Reizdarm-Ursache übersehen. Wird fäkal-oral übertragen, möglicherweise auch über Pinwurm-Eier.',symptoms:['Bauchschmerzen','Durchfall','Blähungen','Reizdarm','Erschöpfung'],cofaktoren:[]},
  {slug:'entamoeba-pcr',name:'Entamoeba histolytica (PCR)',aliases:['entamoeba','amöbe','amöbenruhr'],description:'Einzige pathogene Amöbenart. Kann invasive Amöbiasis (Amöbenruhr) und Leberabszess verursachen. PCR unterscheidet von harmlosen E. dispar.',symptoms:['Blutiger Durchfall','Bauchschmerzen','Fieber','Leberabszess'],cofaktoren:[]},
  {slug:'cryptosporidium-pcr',name:'Cryptosporidium spp. (PCR)',aliases:['cryptosporidium','kryptosporidien'],description:'Opportunistischer Parasit, besonders gefährlich bei Immunsuppression. Übersteht Chlordesinfektion – wasserübertragener Ausbrüche häufig.',symptoms:['Wässriger Durchfall','Bauchkrämpfe','Übelkeit','Gewichtsverlust'],cofaktoren:[]},
  {slug:'cyclospora-pcr',name:'Cyclospora cayetanensis (PCR)',aliases:['cyclospora','cyclospora cayetanensis'],description:'Tropischer Parasit, importiert durch kontaminierte Lebensmittel (Himbeeren, Basilikum). Verursacht prolongierten Durchfall mit Zyklen.',symptoms:['Chronischer Durchfall','Erschöpfung','Übelkeit','Gewichtsverlust'],cofaktoren:[]},
  // ── TUMORMARKER / GENMARKER ─────────────────────────────────────────────────
  {slug:'syndecan-2-methylierung',name:'Syndecan-2-Methylierung (ColoSafe)',aliases:['syndecan-2','syndecan','epigenetisch','darmkrebsvorsorge'],description:'Epigenetischer Marker für kolorektale Neoplasien. Syndecan-2-Gen wird bei Darmkrebs und Adenomen durch Methylierung stillgelegt. 93,7% Übereinstimmung mit Koloskopie.',symptoms:['Blut im Stuhl','Veränderter Stuhlgang','Familiäre Darmkrebsbelastung'],cofaktoren:[]},
  {slug:'okkultes-blut',name:'Okkultes Blut (Hämoglobin, Stuhl)',aliases:['okkultes blut','hämoglobin stuhl','fit','fäkaler immuntest'],description:'Nachweis unsichtbarer Blutspuren im Stuhl via fäkalem Immuntest (FIT). Sensitiver Früherkennungsmarker für kolorektale Neoplasien. Sensitivität für Darmkrebs ~80%.',symptoms:['Blut im Stuhl','Veränderter Stuhlgang','Gewichtsverlust'],cofaktoren:[]},
  {slug:'kras-mutation',name:'KRAS-Mutation (Tumor-DNA)',aliases:['kras','kras-mutation','tumor-dna','onkogen'],description:'KRAS-Punktmutationen in ~40% aller Darmkrebserkrankungen. Nachweis mutierter KRAS-DNA im Stuhl ist hoch spezifisch für Darmkrebs (ColoAlert-Test).',symptoms:['Familiäre Krebsbelastung','Blut im Stuhl','Veränderter Stuhlgang'],cofaktoren:[]},
  {slug:'braf-mutation',name:'BRAF-Mutation (Tumor-DNA)',aliases:['braf','braf-mutation','tumor-dna'],description:'BRAF V600E-Mutation in ~10% der Darmkrebserkrankungen. Zeigt aggressiveren Tumortyp an und ist Therapiemarker (BRAF-Inhibitoren).',symptoms:['Familiäre Krebsbelastung'],cofaktoren:[]},
  {slug:'human-dna',name:'Human-DNA (hDNA, Stuhl)',aliases:['human-dna','hdna','darm-dna'],description:'Nachweis humaner DNA im Stuhl – zeigt Zellabschilfering aus Darmschleimhaut. Erhöhte Konzentration bei Neoplasien (ColoAlert-Komponente).',symptoms:['Blut im Stuhl','Familiäre Krebsbelastung'],cofaktoren:[]},
  // ── VAGINALFLORA ────────────────────────────────────────────────────────────
  {slug:'gardnerella-vaginalis',name:'Gardnerella vaginalis',aliases:['gardnerella','bakterielle vaginose','bv'],description:'Leitbakterie der bakteriellen Vaginose (BV). Verdrängt schützende Lactobazillen → aminartiger Geruch, grau-weißer Fluor, erhöhtes pH > 4,5.',symptoms:['Vaginaler Ausfluss','Geruch','Vaginale Beschwerden'],cofaktoren:[{name:'Probiotika (L. crispatus)',why:'Wiederherstellung vaginaler Lactobazillen'}]},
  {slug:'trichomonas-vaginalis',name:'Trichomonas vaginalis',aliases:['trichomonas','trichomoniasis'],description:'Sexuell übertragbarer Parasit – häufigste nicht-virale STI weltweit. Gelb-grüner, schaumiger Fluor, Juckreiz. Erhöht HIV-Übertragungsrisiko.',symptoms:['Vaginaler Ausfluss','Juckreiz','Brennen','Dyspareurie'],cofaktoren:[]},
  {slug:'vaginalflora-komposition',name:'Vaginalflora-Komposition',aliases:['vaginalflora','laktobazillen-dominanz','cst'],description:'Community State Types (CST) der Vaginalflora: CST I (L. crispatus, optimal) bis CST IV (diverse, wenig Lactobazillen = erhöhtes Risiko). Basis für gezielte Probiotika-Wahl.',symptoms:['Rezidivierende Vaginose','Vaginale Infekte','Dyspareunie'],cofaktoren:[{name:'Probiotika (L. crispatus)',why:'Wiederherstellung CST I'}]},
  {slug:'aromatogramm',name:'Aromatogramm (ätherische Öle)',aliases:['aromatogramm','ätherische öle','naturtherapie'],description:'Empfindlichkeitstestung von Vaginalkeimen gegenüber ätherischen Ölen. Ermöglicht individualisierte naturheilkundliche Therapie bei rezidivierenden Vaginalinfekten.',symptoms:['Rezidivierende Vaginose','Vaginale Infekte'],cofaktoren:[]},
  // ── TRYPTOPHAN-KASKADE ──────────────────────────────────────────────────────
  {slug:'kynurenin',name:'Kynurenin',aliases:['kynurenin','kynurenine','kyn'],description:'Hauptabbauprodukt von Tryptophan (95% Weg). Kynurenin/Tryptophan-Quotient = IDO-Aktivitätsmarker. Erhöht bei chronischer Entzündung → weniger Serotonin.',symptoms:['Depression','Chronische Entzündung','Erschöpfung','Schlafstörung'],cofaktoren:[{name:'Curcumin',why:'Hemmt IDO-Aktivierung'},{name:'Omega-3',why:'Anti-inflammatorisch – senkt IDO-Induktion'}]},
  {slug:'3-oh-kynurenin',name:'3-Hydroxykynurenin',aliases:['3-hydroxykynurenin','3-oh-kynurenin','kmo-produkt'],description:'Intermediat des Kynurenin-Wegs zwischen Kynurenin und Quinolinsäure. Erhöht bei oxidativem Stress – selbst oxidativ und neurotoxisch (Kataraktogenese).',symptoms:['Neuroinflammation','Katarakt','Depression'],cofaktoren:[{name:'Vitamin B6',why:'KAT-Weg als Alternativroute'}]},
  {slug:'nad',name:'NAD⁺ (Nicotinamidadenindinukleotid)',aliases:['nad','nad+','nicotinamid','nicotinamidadenindinukleotid'],description:'Zentraler Energiecarrier und Cofaktor von 500+ Enzymen. NAD+ sinkt mit dem Alter um 50% bis 60. Aktiviert Sirtuine (Anti-Aging-Proteine) und DNA-Reparatur (PARP).',symptoms:['Erschöpfung','Beschleunigtes Altern','Kognitive Abnahme','Muskelschwäche'],cofaktoren:[{name:'Niacinamid (B3)',why:'Direkter NAD-Vorläufer'},{name:'NMN / NR',why:'Effizientere NAD-Vorläufer'}]},
  {slug:'kmo-aktivitaetsindex',name:'KMO-Aktivitätsindex',aliases:['kmo','kynurenin-3-monooxygenase'],description:'KMO leitet Kynurenin zu 3-OH-Kynurenin → Quinolinsäure (neurotoxisch). Erhöhter KMO-Index = mehr Neuroinflammation. Zielstruktur für neue Antidepressiva.',symptoms:['Depression','Neuroinflammation','Chronische Erschöpfung'],cofaktoren:[{name:'NAC',why:'Hemmt KMO indirekt'}]},
  // ── LONGEVITY / SPEZIAL ─────────────────────────────────────────────────────
  {slug:'helicobacter-pylori-ag',name:'Helicobacter pylori Antigen (Stuhl)',aliases:['helicobacter','h. pylori','hp antigen','magengeschwür'],description:'H. pylori besiedelt Magenschleimhaut bei ~40% der Deutschen. Verursacht chronische Gastritis, Ulzera und erhöht Magenkrebs-Risiko 3-6fach. Stuhl-Antigentest sensitiver als Atemtest.',symptoms:['Magenschmerzen','Sodbrennen','Übelkeit','Völlegefühl','Blähungen','Appetitlosigkeit'],cofaktoren:[{name:'Probiotika (L. reuteri)',why:'Hemmt H. pylori-Adhäsion'},{name:'Mastix-Harz',why:'Pflanzlich anti-H.-pylori'}]},
  {slug:'enterococcus-faecalis',name:'Enterococcus faecalis',aliases:['enterococcus','e. faecalis','enterokokken'],description:'Normalflora-Bakterium, kann aber bei Dysbiose pathogen werden. Im vaginalen Kontext (Aromatogramm): verursacht rezidivierende Infekte. Antibiotika-Resistenzen häufig.',symptoms:['Vaginale Infekte','Harnwegsinfekte','Rezidivierende Infekte'],cofaktoren:[]},
];

// ── MAPPINGS: (test_id, biomarker_slug, pct, note) ──────────────────────────
const MAP = [
  // prevent-360 (75 Parameter)
  ['prevent-360','tryptophan',88,'Tryptophan im Aminosäure-Vollprofil'],
  ['prevent-360','leucin',85,'Leucin als BCAA im Profil'],
  ['prevent-360','isoleucin',85,'Isoleucin als BCAA'],
  ['prevent-360','valin',85,'Valin als BCAA'],
  ['prevent-360','methionin',88,'Methionin + Homocystein-Methylierung'],
  ['prevent-360','phenylalanin',85,'Phenylalanin im Aminosäureprofil'],
  ['prevent-360','tyrosin',88,'Tyrosin – Dopamin-Vorläufer'],
  ['prevent-360','threonin',82,'Threonin im Aminosäureprofil'],
  ['prevent-360','lysin',82,'Lysin im Aminosäureprofil'],
  ['prevent-360','arginin',85,'Arginin für NO-Synthese'],
  ['prevent-360','glutamin',82,'Glutamin im Darm-Check'],
  ['prevent-360','glycin',80,'Glycin im Aminosäureprofil'],
  ['prevent-360','serin',80,'Serin im Aminosäureprofil'],
  ['prevent-360','alanin',80,'Alanin im Aminosäureprofil'],
  ['prevent-360','taurin',85,'Taurin – Herz und Neurotransmitter'],
  ['prevent-360','citrullin',82,'Citrullin – NO-Marker'],
  ['prevent-360','ornithin',78,'Ornithin im Harnstoffzyklus'],
  ['prevent-360','homocystein',88,'Homocystein als Methylierungs-Marker'],
  ['prevent-360','histidin',78,'Histidin im Aminosäureprofil'],
  ['prevent-360','dopamin',80,'Dopamin-Metabolite im 360-Profil'],
  ['prevent-360','serotonin',80,'Serotonin/IDO-Aktivität im Profil'],
  ['prevent-360','gaba',78,'GABA im Neurochemie-Screening'],
  ['prevent-360','cortisol-morgens',78,'Cortisol im 360-Profil'],
  ['prevent-360','dhea',78,'DHEA im Hormonscreening'],
  ['prevent-360','testosteron',75,'Testosteron im 360-Profil'],
  ['prevent-360','estradiol',72,'Estradiol im 360-Profil'],
  ['prevent-360','tsh',78,'TSH Schilddrüsen-Screening'],
  ['prevent-360','vitamin-d3',88,'Vitamin D3 (25-OH)'],
  ['prevent-360','vitamin-b12',88,'Vitamin B12'],
  ['prevent-360','folsaeure',85,'Folsäure (B9)'],
  ['prevent-360','vitamin-b6',82,'Vitamin B6 (P5P)'],
  ['prevent-360','vitamin-e',78,'Vitamin E (Tocopherol)'],
  ['prevent-360','coq10',75,'CoQ10 (Ubiquinol)'],
  ['prevent-360','magnesium',85,'Magnesium intrazellulär'],
  ['prevent-360','zink',82,'Zink intrazellulär'],
  ['prevent-360','selen',80,'Selen intrazellulär'],
  ['prevent-360','eisen',82,'Eisen intrazellulär'],
  ['prevent-360','ferritin',80,'Ferritin im Profil'],
  ['prevent-360','kupfer',78,'Kupfer intrazellulär'],
  ['prevent-360','calcium',78,'Calcium intrazellulär'],
  ['prevent-360','jod',68,'Jod-Status aus Selen+TSH ableitbar'],
  ['prevent-360','epa',75,'EPA im Fettsäureprofil'],
  ['prevent-360','dha',75,'DHA im Fettsäureprofil'],
  ['prevent-360','hscrp',88,'hsCRP Entzündungsmarker'],
  ['prevent-360','gesamt-cholesterin',85,'Gesamtcholesterin'],
  ['prevent-360','hdl-cholesterin',85,'HDL-Cholesterin'],
  ['prevent-360','ldl-cholesterin',85,'LDL-Cholesterin'],
  ['prevent-360','triglyzeride',85,'Triglyzeride'],
  ['prevent-360','histamin-stuhl',75,'Histamin/Histidin im Profil'],
  ['prevent-360','ido-aktivitaet',80,'IDO-Aktivität via Kyn/Trp-Quotient'],
  // om-vital
  ['om-vital','hscrp',94,'hsCRP im OM-Vital'],
  ['om-vital','gesamt-cholesterin',94,'Gesamtcholesterin im OM-Vital'],
  ['om-vital','hdl-cholesterin',94,'HDL-Cholesterin'],
  ['om-vital','ldl-cholesterin',94,'LDL-Cholesterin'],
  ['om-vital','triglyzeride',94,'Triglyzeride'],
  ['om-vital','tsh',92,'TSH Schilddrüse im OM-Vital'],
  ['om-vital','vitamin-d3',92,'Vitamin D3 (25-OH)'],
  ['om-vital','vitamin-b12',92,'Vitamin B12'],
  ['om-vital','folsaeure',88,'Folsäure'],
  ['om-vital','vitamin-e',88,'Vitamin E (Tocopherol)'],
  ['om-vital','coq10',88,'CoQ10 (Ubiquinol)'],
  ['om-vital','ferritin',88,'Ferritin (Eisenspeicher)'],
  ['om-vital','selen',88,'Selen'],
  ['om-vital','kupfer',85,'Kupfer'],
  ['om-vital','zink',82,'Zink'],
  ['om-vital','homocystein',78,'Homocystein im OM-Vital'],
  // vitamincheck-basis
  ['vitamincheck-basis','vitamin-d3',96,'Vitamin D3 (25-OH) – direkter Test'],
  ['vitamincheck-basis','vitamin-b12',96,'Vitamin B12 (Cobalamin)'],
  ['vitamincheck-basis','folsaeure',96,'Folsäure (B9)'],
  ['vitamincheck-basis','vitamin-e',95,'Vitamin E (alpha-Tocopherol)'],
  ['vitamincheck-basis','coq10',95,'CoQ10 (Ubiquinol)'],
  // vollblutmineralanalyse
  ['vollblutmineralanalyse','magnesium',97,'Magnesium intrazellulär im Vollblut'],
  ['vollblutmineralanalyse','zink',97,'Zink intrazellulär'],
  ['vollblutmineralanalyse','selen',97,'Selen intrazellulär'],
  ['vollblutmineralanalyse','eisen',97,'Eisen intrazellulär'],
  ['vollblutmineralanalyse','kupfer',97,'Kupfer intrazellulär'],
  ['vollblutmineralanalyse','calcium',97,'Calcium intrazellulär'],
  ['vollblutmineralanalyse','natrium',97,'Natrium intrazellulär'],
  ['vollblutmineralanalyse','kalium',97,'Kalium intrazellulär'],
  // nitrostress
  ['nitrostress','4-hydroxynitrophenyl-essigsaeure',97,'RNS-Marker – nitrosativer Stress'],
  ['nitrostress','methylmalonsaeure',92,'MMA – mitochondriale Funktion'],
  ['nitrostress','citrullin',90,'Citrullin – NO-Stoffwechsel'],
  ['nitrostress','kreatinin',85,'Kreatinin als Urin-Referenz'],
  // neurotransmitter-plus
  ['neurotransmitter-plus','adrenalin',96,'Adrenalin direkt im Urin'],
  ['neurotransmitter-plus','noradrenalin',96,'Noradrenalin direkt'],
  ['neurotransmitter-plus','dopamin',96,'Dopamin direkt'],
  ['neurotransmitter-plus','serotonin',96,'Serotonin direkt'],
  ['neurotransmitter-plus','glutamat',96,'Glutamat direkt'],
  ['neurotransmitter-plus','gaba',96,'GABA direkt'],
  // sibo
  ['sibo','h2-atemgas',97,'H₂-Atemgas nach Lactulose – SIBO-Goldstandard'],
  ['sibo','ch4-atemgas',97,'CH₄-Atemgas – Methan-SIBO'],
  ['sibo','citrullin',72,'Citrullin indirekt: Dünndarmzellen-Marker'],
  // laktose-atemtest
  ['laktose-atemtest','laktose-h2',97,'H₂ nach Laktose-Belastung'],
  ['laktose-atemtest','h2-atemgas',90,'H₂-Verlaufskurve über Messzeitraum'],
  // fruktose-atemtest
  ['fruktose-atemtest','fruktose-h2',97,'H₂ nach Fruktose-Belastung'],
  ['fruktose-atemtest','h2-atemgas',90,'H₂-Verlaufskurve Fruktose'],
  // igg-lebensmitteltest
  ['igg-lebensmitteltest','igg-lebensmittel',97,'IgG Klassen 0-4 gegen 270 Lebensmittel'],
  // gliadin-tg2
  ['gliadin-tg2','anti-gliadin-aga',97,'Anti-Gliadin IgA/IgG direkt'],
  ['gliadin-tg2','anti-tg2',97,'Anti-TG2 – Zöliakie-Goldstandard'],
  ['gliadin-tg2','zonulin',65,'Gluten aktiviert Zonulin-Freisetzung'],
  // organische-saure
  ['organische-saure','pyruvat',92,'Pyruvat im OA-Profil'],
  ['organische-saure','laktat',90,'Laktat im OA-Profil'],
  ['organische-saure','zitrat',90,'Zitrat (Zitratzyklus)'],
  ['organische-saure','alpha-ketoglutarat',90,'Alpha-Ketoglutarat (Krebs-Zyklus)'],
  ['organische-saure','fumarat',88,'Fumarat im Zitratzyklus'],
  ['organische-saure','malat',88,'Malat im Zitratzyklus'],
  ['organische-saure','succinat',88,'Succinat im Zitratzyklus'],
  ['organische-saure','3-hydroxybutyrat',85,'Beta-Hydroxybutyrat (Ketone)'],
  ['organische-saure','methylmalonsaeure',92,'Methylmalonsäure – B12-Marker'],
  ['organische-saure','kynurensaeure',85,'Kynurensäure im OA-Profil'],
  ['organische-saure','quinolinsaeure',85,'Quinolinsäure – Neuroinflammation'],
  ['organische-saure','8-ohdg',85,'8-OHdG DNA-Oxidationsmarker'],
  ['organische-saure','4-hydroxynitrophenyl-essigsaeure',82,'RNS-Marker'],
  ['organische-saure','citrullin',80,'Citrullin – NO-Marker'],
  ['organische-saure','kreatinin',85,'Kreatinin-Referenz'],
  // cortisol-tagesprofil
  ['cortisol-tagesprofil','cortisol-morgens',97,'Cortisol 08:00 (CAR-Peak)'],
  ['cortisol-tagesprofil','cortisol-mittags',97,'Cortisol 12:00'],
  ['cortisol-tagesprofil','cortisol-abends',97,'Cortisol 20:00'],
  ['cortisol-tagesprofil','dhea',94,'DHEA – Nebennierenreserve'],
  // hormonprofil-frau
  ['hormonprofil-frau','estradiol',97,'Estradiol (E2) aus Speichel'],
  ['hormonprofil-frau','progesteron',97,'Progesteron aus Speichel'],
  ['hormonprofil-frau','testosteron',92,'Testosteron bei der Frau'],
  ['hormonprofil-frau','cortisol-morgens',88,'Cortisol im Frauen-Profil'],
  ['hormonprofil-frau','dhea',88,'DHEA im Frauen-Profil'],
  // mann-hormonprofil-test
  ['mann-hormonprofil-test','testosteron',97,'Testosteron aus Speichel'],
  ['mann-hormonprofil-test','estradiol',88,'Estradiol (Aromatase-Marker)'],
  ['mann-hormonprofil-test','progesteron',85,'Progesteron'],
  ['mann-hormonprofil-test','cortisol-morgens',88,'Cortisol im Mann-Profil'],
  ['mann-hormonprofil-test','dhea',88,'DHEA – Nebennierenreserve'],
  // melatonin
  ['melatonin','melatonin',97,'Melatonin aus Nachtspeichel – einziger direkter Test'],
  // stress-erschoepfung-test
  ['stress-erschoepfung-test','adrenalin',92,'Adrenalin im Stress-Profil'],
  ['stress-erschoepfung-test','noradrenalin',92,'Noradrenalin im Stress-Profil'],
  ['stress-erschoepfung-test','dopamin',92,'Dopamin im Stress-Profil'],
  ['stress-erschoepfung-test','serotonin',90,'Serotonin im Stress-Profil'],
  ['stress-erschoepfung-test','glutamat',88,'Glutamat im Profil'],
  ['stress-erschoepfung-test','gaba',88,'GABA im Stress-Profil'],
  // omega-3
  ['omega-3-test-fettsaure-analyse','epa',97,'EPA in Erythrozyten – Goldstandard'],
  ['omega-3-test-fettsaure-analyse','dha',97,'DHA in Erythrozyten'],
  ['omega-3-test-fettsaure-analyse','ala',92,'ALA (pflanzliches Omega-3)'],
  ['omega-3-test-fettsaure-analyse','linolsaeure',92,'Linolsäure (Omega-6)'],
  ['omega-3-test-fettsaure-analyse','arachidonsaeure',92,'Arachidonsäure'],
  ['omega-3-test-fettsaure-analyse','omega6-3-quotient',95,'Omega-6/3-Quotient'],
  ['omega-3-test-fettsaure-analyse','epa-aa-quotient',95,'EPA/AA-Quotient'],
  ['omega-3-test-fettsaure-analyse','transfettsaeuren',90,'Transfettsäuren'],
  // zellstressprofil
  ['zellstressprofil','8-ohdg',97,'8-OHdG – direkter DNA-Oxidationsmarker'],
  ['zellstressprofil','4-hydroxynitrophenyl-essigsaeure',95,'Nitrosativer Stress (RNS)'],
  ['zellstressprofil','methylmalonsaeure',90,'MMA – mitochondriale Funktion'],
  ['zellstressprofil','citrullin',88,'Citrullin – NO-Metabolismus'],
  ['zellstressprofil','kreatinin',85,'Kreatinin-Referenz'],
  // jod-1
  ['jod-1','jod',97,'Jod-Ausscheidung im Morgenurin'],
  // darmmikrobiom-analyse
  ['darmmikrobiom-analyse','lactobacillus',94,'Lactobacillus im Stuhl'],
  ['darmmikrobiom-analyse','bifidobacterium',94,'Bifidobacterium im Stuhl'],
  ['darmmikrobiom-analyse','akkermansia',88,'Akkermansia muciniphila'],
  ['darmmikrobiom-analyse','faecalibacterium',88,'Faecalibacterium prausnitzii'],
  ['darmmikrobiom-analyse','candida',90,'Candida/Hefen im Stuhl'],
  ['darmmikrobiom-analyse','pankreas-elastase',85,'Pankreatische Elastase-1'],
  ['darmmikrobiom-analyse','sekretorisches-iga',90,'Sekretorisches IgA'],
  ['darmmikrobiom-analyse','zonulin',94,'Zonulin – Leaky Gut'],
  ['darmmikrobiom-analyse','histamin-stuhl',85,'Histamin im Stuhl'],
  ['darmmikrobiom-analyse','calprotectin',88,'Calprotectin – Darmentzündung'],
  ['darmmikrobiom-analyse','beta-glucuronidase',82,'ß-Glucuronidase – Östrogenrecycling'],
  ['darmmikrobiom-analyse','mikrobiom-diversitaet',92,'Mikrobiom-Diversität'],
  ['darmmikrobiom-analyse','dysbiose-index',90,'Dysbiose-Index'],
  // histamin-dao-analyse
  ['histamin-dao-analyse','dao-enzym',97,'DAO-Enzymaktivität direkt'],
  ['histamin-dao-analyse','histamin-stuhl',97,'Histamin im Stuhl'],
  // darmgesundheit-check-up
  ['darmgesundheit-check-up','mikrobiom-diversitaet',92,'Mikrobiom-Komposition vollständig'],
  ['darmgesundheit-check-up','candida',88,'Hefen & Pilze'],
  ['darmgesundheit-check-up','blastocystis-pcr',90,'Parasiten-PCR Blastocystis'],
  ['darmgesundheit-check-up','giardia-pcr',90,'Parasiten-PCR Giardia'],
  ['darmgesundheit-check-up','dientamoeba-pcr',90,'Parasiten-PCR Dientamoeba'],
  ['darmgesundheit-check-up','zonulin',92,'Zonulin – Leaky Gut'],
  ['darmgesundheit-check-up','calprotectin',92,'Calprotectin – Darmentzündung'],
  ['darmgesundheit-check-up','sekretorisches-iga',88,'Sekretorisches IgA'],
  ['darmgesundheit-check-up','pankreas-elastase',85,'Pankreatische Elastase'],
  ['darmgesundheit-check-up','gallensaeuren',82,'Gallensäuren-Metabolismus'],
  ['darmgesundheit-check-up','h2-atemgas',90,'SIBO H₂-Atemtest'],
  ['darmgesundheit-check-up','ch4-atemgas',90,'SIBO CH₄-Atemtest'],
  ['darmgesundheit-check-up','histamin-stuhl',88,'Histamin im Stuhl'],
  ['darmgesundheit-check-up','tryptophan',82,'Tryptophan (Darm-Hirn-Achse)'],
  ['darmgesundheit-check-up','serotonin',78,'Serotonin intestinal'],
  ['darmgesundheit-check-up','gaba',75,'GABA intestinal'],
  ['darmgesundheit-check-up','dao-enzym',85,'DAO-Enzym'],
  ['darmgesundheit-check-up','beta-glucuronidase',80,'ß-Glucuronidase'],
  ['darmgesundheit-check-up','helicobacter-pylori-ag',72,'H. pylori Screening'],
  // longevity-check-up
  ['longevity-check-up','tryptophan',82,'Tryptophan im Longevity-Panel'],
  ['longevity-check-up','leucin',80,'Leucin (BCAA)'],
  ['longevity-check-up','homocystein',88,'Homocystein – Methylierung'],
  ['longevity-check-up','epa',90,'EPA im Longevity-Panel'],
  ['longevity-check-up','dha',90,'DHA'],
  ['longevity-check-up','omega6-3-quotient',88,'Omega-6/3-Quotient'],
  ['longevity-check-up','vitamin-d3',92,'Vitamin D3'],
  ['longevity-check-up','zink',88,'Zink'],
  ['longevity-check-up','magnesium',90,'Magnesium'],
  ['longevity-check-up','eisen',85,'Eisen'],
  ['longevity-check-up','ferritin',85,'Ferritin'],
  ['longevity-check-up','cortisol-morgens',90,'Cortisol-Profil'],
  ['longevity-check-up','cortisol-abends',90,'Cortisol abends'],
  ['longevity-check-up','dhea',90,'DHEA – Nebennierenreserve'],
  ['longevity-check-up','hscrp',88,'Entzündungsmarker hsCRP'],
  ['longevity-check-up','gallensaeuren',78,'Gallensäuren'],
  ['longevity-check-up','nad',88,'NAD – Longevity-Marker'],
  ['longevity-check-up','mikrobiom-diversitaet',85,'Mikrobiom-Diversität'],
  ['longevity-check-up','testosteron',90,'Testosteron'],
  ['longevity-check-up','estradiol',88,'Estradiol'],
  ['longevity-check-up','progesteron',85,'Progesteron'],
  ['longevity-check-up','8-ohdg',90,'8-OHdG – DNA-Stabilität'],
  // schlaf-stress-paket
  ['schlaf-stress-paket','8-ohdg',92,'8-OHdG Zellstress'],
  ['schlaf-stress-paket','4-hydroxynitrophenyl-essigsaeure',90,'Nitrosativer Stress'],
  ['schlaf-stress-paket','methylmalonsaeure',88,'MMA'],
  ['schlaf-stress-paket','cortisol-morgens',95,'Cortisol morgens'],
  ['schlaf-stress-paket','cortisol-mittags',95,'Cortisol mittags'],
  ['schlaf-stress-paket','cortisol-abends',95,'Cortisol abends'],
  ['schlaf-stress-paket','dhea',92,'DHEA'],
  ['schlaf-stress-paket','melatonin',94,'Melatonin Nachtspeichel'],
  ['schlaf-stress-paket','adrenalin',90,'Adrenalin'],
  ['schlaf-stress-paket','noradrenalin',90,'Noradrenalin'],
  ['schlaf-stress-paket','dopamin',90,'Dopamin'],
  ['schlaf-stress-paket','serotonin',90,'Serotonin'],
  ['schlaf-stress-paket','gaba',88,'GABA'],
  // helicobacter-pylori
  ['helicobacter-pylori','helicobacter-pylori-ag',97,'H. pylori Antigen im Stuhl'],
  // mikrobolom
  ['mikrobolom','mikrobiom-diversitaet',95,'16S-rRNA Diversitätsanalyse'],
  ['mikrobolom','dysbiose-index',92,'Funktionelle Bakteriengruppen'],
  ['mikrobolom','serotonin',72,'Serotonin intestinal'],
  ['mikrobolom','gaba',70,'GABA intestinal'],
  ['mikrobolom','sekretorisches-iga',88,'Immunfunktion sIgA'],
  ['mikrobolom','zonulin',75,'Barrierefunktion'],
  ['mikrobolom','gallensaeuren',82,'Gallensäure-Metabolismus'],
  ['mikrobolom','lps-toxine',78,'LPS-Endotoxine'],
  ['mikrobolom','candida',85,'Hefen (Candida)'],
  ['mikrobolom','blastocystis-pcr',72,'Parasiten-Screening'],
  ['mikrobolom','calprotectin',70,'Entzündungsmarker'],
  // colosafe
  ['colosafe','syndecan-2-methylierung',97,'Syndecan-2-Methylierung epigenetisch'],
  // hautgesundheit-basis
  ['hautgesundheit-basis','mikrobiom-diversitaet',88,'Bakterielle Diversität'],
  ['hautgesundheit-basis','dysbiose-index',85,'Dysbiose-Index'],
  ['hautgesundheit-basis','faecalibacterium',80,'Butyrat-Produzenten'],
  ['hautgesundheit-basis','candida',85,'Pilze/Candida'],
  ['hautgesundheit-basis','zink',92,'Zink (Haut)'],
  ['hautgesundheit-basis','magnesium',88,'Magnesium'],
  ['hautgesundheit-basis','kupfer',88,'Kupfer'],
  ['hautgesundheit-basis','eisen',85,'Eisen'],
  ['hautgesundheit-basis','calcium',85,'Calcium'],
  ['hautgesundheit-basis','selen',88,'Selen'],
  ['hautgesundheit-basis','testosteron',82,'Testosteron (Akne-Marker)'],
  // vaginalflora
  ['vaginalflora','vaginalflora-komposition',97,'Vaginalflora-Komposition (CST)'],
  ['vaginalflora','lactobacillus',95,'Lactobacillus-Arten'],
  ['vaginalflora','gardnerella-vaginalis',92,'Gardnerella vaginalis'],
  ['vaginalflora','trichomonas-vaginalis',92,'Trichomonas vaginalis'],
  ['vaginalflora','candida',88,'Candida spp.'],
  ['vaginalflora','enterococcus-faecalis',88,'Enterococcus faecalis'],
  ['vaginalflora','aromatogramm',90,'Aromatogramm für Naturtherapie'],
  // profil-parasiten-pcr
  ['profil-parasiten-pcr','blastocystis-pcr',97,'Blastocystis hominis PCR'],
  ['profil-parasiten-pcr','giardia-pcr',97,'Giardia lamblia PCR'],
  ['profil-parasiten-pcr','dientamoeba-pcr',97,'Dientamoeba fragilis PCR'],
  ['profil-parasiten-pcr','entamoeba-pcr',97,'Entamoeba histolytica PCR'],
  ['profil-parasiten-pcr','cryptosporidium-pcr',97,'Cryptosporidium PCR'],
  ['profil-parasiten-pcr','cyclospora-pcr',97,'Cyclospora cayetanensis PCR'],
  // tryptophan-metabolismus
  ['tryptophan-metabolismus','tryptophan',97,'Tryptophan vollständig'],
  ['tryptophan-metabolismus','kynurenin',97,'Kynurenin'],
  ['tryptophan-metabolismus','kynurensaeure',97,'Kynurensäure'],
  ['tryptophan-metabolismus','3-oh-kynurenin',97,'3-Hydroxykynurenin'],
  ['tryptophan-metabolismus','quinolinsaeure',97,'Quinolinsäure – Neurotoxin-Marker'],
  ['tryptophan-metabolismus','nad',90,'NAD-Status'],
  ['tryptophan-metabolismus','serotonin',88,'Serotonin'],
  ['tryptophan-metabolismus','ido-aktivitaet',97,'IDO-Aktivitätsindex'],
  ['tryptophan-metabolismus','kmo-aktivitaetsindex',97,'KMO-Aktivitätsindex'],
  ['tryptophan-metabolismus','kreatinin',85,'Kreatinin-Referenz'],
  // beta-glucuronidase
  ['beta-glucuronidase','beta-glucuronidase',97,'ß-Glucuronidase Aktivität direkt'],
  // coloalert
  ['coloalert','okkultes-blut',97,'Okkultes Blut (FIT)'],
  ['coloalert','kras-mutation',97,'KRAS-Mutation Tumor-DNA'],
  ['coloalert','braf-mutation',97,'BRAF-Mutation'],
  ['coloalert','human-dna',92,'Human-DNA (hDNA)'],
];

async function run() {
  console.log('🚀 Migration 2 — Einzelparameter...\n');

  // Insert biomarkers
  console.log(`📊 Inserting ${BM.length} individual biomarkers...`);
  const { error: bme } = await sb.from('bm_biomarkers').upsert(
    BM.map(b => ({ slug:b.slug, name:b.name, aliases:b.aliases, description:b.description, symptoms:b.symptoms, cofaktoren:b.cofaktoren })),
    { onConflict: 'slug' }
  );
  if (bme) { console.error('BM error:', bme.message); return; }
  console.log(`✅ ${BM.length} Biomarker inserted`);

  // Fetch IDs
  const { data: bms } = await sb.from('bm_biomarkers').select('id, slug');
  const slugToId = Object.fromEntries(bms.map(b => [b.slug, b.id]));

  // Insert mappings
  const mappingData = MAP.map(([t, b, pct, note]) => ({
    test_id: t, biomarker_id: slugToId[b], coverage_pct: pct, note
  })).filter(m => m.biomarker_id);

  const missing = MAP.filter(([,b]) => !slugToId[b]).map(([,b]) => b);
  if (missing.length) console.warn('⚠️  Missing slugs:', [...new Set(missing)]);

  console.log(`🔗 Inserting ${mappingData.length} mappings...`);
  const { error: me } = await sb.from('bm_test_biomarkers').upsert(mappingData, { onConflict: 'test_id,biomarker_id' });
  if (me) { console.error('Mapping error:', me.message); return; }

  const { count: bc } = await sb.from('bm_biomarkers').select('*',{count:'exact',head:true});
  const { count: mc } = await sb.from('bm_test_biomarkers').select('*',{count:'exact',head:true});
  console.log(`\n📊 Datenbank:\n   Biomarker: ${bc}\n   Mappings:  ${mc}\n✅ Fertig!`);
}

run().catch(console.error);
