import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://alazsyhlydhimfqpdros.supabase.co';
const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYXpzeWhseWRoaW1mcXBkcm9zIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODYzNDcyMSwiZXhwIjoyMDk0MjEwNzIxfQ.Veyo2POB-egtBhQSCewegNpj6ucYZ8f2Tt8Q0yKJCRo';
const sb = createClient(SUPABASE_URL, SERVICE_KEY);

// ─── TESTS DATA ────────────────────────────────────────────────
const TESTS = [
  { id:'prevent-360', name:'Prevent 360', price:'325,00 €', sub:'75 Parameter · Kapillarblut · Heimtest', sample:'Kapillarblut (120 µl)', shop_slug:'prevent-360-ory-analysis-test', cat:'Komplex-Profile', cat_key:'komplex', tags:['Aminosäuren','Hormone','Neurotransmitter','Vitamine','Mineralstoffe','Herzmarker'], keywords:['prevent','360','komplex','aminosäuren','cortisol','dhea','gaba','histamin'], description:'Das umfassendste ORY-Profil: 75 Parameter aus 120 µl Kapillarblut.', biomarker_names:['Tryptophan','Leucin','Isoleucin','Arginin','Taurin','Tyrosin','Glutamin','Glycin','Serin','Alanin','Cortisol','DHEA','GABA','IDO-Aktivität','Histamin / Histidin','hs-CRP','Gesamt-Cholesterin','HDL','LDL','Triglyzeride'] },
  { id:'om-vital', name:'OM Vital Bluttest', price:'205,00 €', sub:'Stoffwechsel + Vitamine + Entzündung · Kapillarblut', sample:'Kapillarblut', shop_slug:'om-vital-bluttest', cat:'Komplex-Profile', cat_key:'komplex', tags:['hsCRP','Cholesterin','Vitamin D','B12','Folsäure','CoQ10','Selen','Ferritin','TSH','Leberwerte'], keywords:['om vital','stoffwechsel','entzündung','cholesterin','tsh','crp'], description:'Umfassendes Stoffwechsel- und Vitalstoff-Screening aus Kapillarblut.', biomarker_names:['hs-CRP','Gesamt-Cholesterin','HDL','LDL','Triglyzeride','TSH','Vitamin D3 (25-OH)','Vitamin B12','Folsäure','Vitamin E','Coenzym Q10','Ferritin (Eisen)','Selen','Kupfer'] },
  { id:'vitamincheck-basis', name:'Vitamincheck Basis', price:'98,50 €', sub:'5 Parameter · Kapillarblut · Heimtest', sample:'Kapillarblut', shop_slug:'vitamincheck-basis', cat:'Vitamine & Nährstoffe', cat_key:'vitamine', tags:['Vitamin D3','Vitamin B12','Folsäure','Vitamin E','CoQ10'], keywords:['vitamincheck','vitamin d','b12','folsäure','vitamin e','coq10'], description:'Die fünf wichtigsten Vitamine und Mikronährstoffe im Basischeck.', biomarker_names:['Folsäure (B9)','Vitamin B12','Vitamin D3 (25-OH)','Vitamin E (Tocopherol)','Coenzym Q10 (Ubiquinol)'] },
  { id:'vollblutmineralanalyse', name:'Vollblutmineralanalyse', price:'75,00 €', sub:'8 Mineralstoffe intrazellulär · Kapillarblut · Heimtest', sample:'Kapillarblut', shop_slug:'vollblutmineralanalyse', cat:'Mineralstoffe', cat_key:'mineralstoffe', tags:['Magnesium','Zink','Selen','Eisen','Kupfer','Calcium','Natrium','Kalium'], keywords:['mineralanalyse','magnesium','zink','selen','eisen','kupfer','calcium','vollblut'], description:'8 Mineralstoffe intrazellulär gemessen – aussagekräftiger als Serum.', biomarker_names:['Natrium (Na)','Kalium (K)','Calcium (Ca)','Magnesium (Mg)','Eisen (Fe)','Kupfer (Cu)','Zink (Zn)','Selen (Se)'] },
  { id:'nitrostress', name:'Nitrostress', price:'89,00 €', sub:'4 Parameter · Urin · Heimtest', sample:'Urin (Morgenurin)', shop_slug:'nitrostress-nitrosativer-stress', cat:'Stoffwechsel', cat_key:'stoff', tags:['Nitrosativer Stress','RNS','Methylmalonsäure','Citrullin'], keywords:['nitrostress','nitrosativer stress','rns','oxidativer stress','citrullin','methylmalonsäure'], description:'Misst nitrosativen Stress: reaktive Stickstoffspezies (RNS) und Mitochondrienfunktion.', biomarker_names:['Nitrophenylessigsäure (RNS-Belastung)','Methylmalonsäure (mitochondriale Funktion)','Citrullin (NO-Stoffwechsel)','Kreatinin (Referenz)'] },
  { id:'neurotransmitter-plus', name:'Neurotransmitter Plus', price:'145,00 €', sub:'6 Neurotransmitter · Urin · Heimtest', sample:'Urin (Morgenurin)', shop_slug:'neurotransmitter-plus', cat:'Neurotransmitter', cat_key:'neuro', tags:['Dopamin','Serotonin','GABA','Adrenalin','Noradrenalin','Glutamat'], keywords:['neurotransmitter','dopamin','serotonin','gaba','adrenalin','noradrenalin','glutamat'], description:'6 Neurotransmitter aus Urin – Einblick in Gehirnchemie und Stressreaktion.', biomarker_names:['Adrenalin (Stressreaktion)','Noradrenalin (Aufmerksamkeit)','Dopamin (Motivation, Belohnung)','Serotonin (Stimmung, Schlaf)','Glutamat (Erregung)','GABA (Hemmung, Beruhigung)'] },
  { id:'sibo', name:'SIBO Atemtest', price:'89,00 €', sub:'H₂ + CH₄ Atemgas · 90 min · Heimtest', sample:'Atemgas (Lactulose-Provokation)', shop_slug:'sibo', cat:'Darm & Verdauung', cat_key:'darm', tags:['SIBO','Blähungen','Dünndarm','Wasserstoff','Methan','Bakterien'], keywords:['sibo','blähungen','reizdarm','atemtest','wasserstoff','methan','lactulose'], description:'Erkennt SIBO durch Messung von H₂ und CH₄ in der Atemluft.', biomarker_names:['Wasserstoff (H₂) in der Atemluft','Methan (CH₄) in der Atemluft','Gasverlauf über 90 Minuten nach Lactulose'] },
  { id:'laktose-atemtest', name:'Laktose-Atemtest', price:'69,00 €', sub:'H₂ · Atemgas · Heimtest', sample:'Atemgas (Laktose-Belastung)', shop_slug:'laktose-atemgastest', cat:'Darm & Verdauung', cat_key:'darm', tags:['Laktose','Milchzucker','Intoleranz','H₂','Dünndarm','Verdauung'], keywords:['laktose','milchzucker','laktoseintoleranz','atemtest','h2','wasserstoff'], description:'Misst Laktose-Verarbeitung im Darm durch Atemgasanalyse.', biomarker_names:['H₂-Konzentration in Atemluft nach Laktose-Belastung','Gasverlauf-Kurve über den Messzeitraum'] },
  { id:'fruktose-atemtest', name:'Fruktose-Atemtest', price:'69,00 €', sub:'H₂ · Atemgas · Heimtest', sample:'Atemgas (Fruktose-Belastung)', shop_slug:'fruktose-absorptions-analyse-atemtest-parameter', cat:'Darm & Verdauung', cat_key:'darm', tags:['Fruktose','Fruchtzucker','Intoleranz','FODMAP','H₂'], keywords:['fruktose','fruchtzucker','fruktoseintoleranz','atemtest','fodmap','glut5'], description:'Erkennt Fruktose-Malabsorption durch Atemgasanalyse.', biomarker_names:['H₂-Konzentration nach Fruktose-Belastung','Absorptionsverlauf-Kurve'] },
  { id:'igg-lebensmitteltest', name:'IgG-Lebensmitteltest', price:'149,00 €', sub:'270 Lebensmittel · Kapillarblut · Heimtest', sample:'Kapillarblut', shop_slug:'igg-antikorper-analyse-bluttest-fuer-270-lebensmittel', cat:'Darm & Verdauung', cat_key:'darm', tags:['IgG','Nahrungsmittelunverträglichkeit','Leaky Gut','Entzündung'], keywords:['igg','nahrungsmittelunverträglichkeit','lebensmitteltest','270','antikörper','leaky gut'], description:'IgG-Antikörper gegen 270 Lebensmittel – erkennt verzögerte Unverträglichkeiten.', biomarker_names:['IgG-Antikörper gegen 270 Lebensmittelbestandteile (Klassen 0–4)'] },
  { id:'gliadin-tg2', name:'Gliadin & TG2-Antikörper', price:'65,00 €', sub:'2 Marker · Stuhl · Heimtest', sample:'Stuhl', shop_slug:'gliadin-und-transglutaminase-im-stuhl', cat:'Darm & Verdauung', cat_key:'darm', tags:['Gluten','Zöliakie','Gliadin','Transglutaminase','TG2'], keywords:['gliadin','tg2','transglutaminase','zöliakie','gluten','weizenallergie','stuhl'], description:'Erkennt Glutenunverträglichkeit und Zöliakie durch Stuhltest.', biomarker_names:['Anti-Gliadin-Antikörper (AGA)','Anti-Transglutaminase-2-Antikörper (anti-TG2)'] },
  { id:'organische-saure', name:'Organische Säuren', price:'189,00 €', sub:'30+ Parameter · Urin · Heimtest', sample:'Urin (Morgenurin)', shop_slug:'organische-saure', cat:'Stoffwechsel', cat_key:'stoff', tags:['Mitochondrien','Energiestoffwechsel','Krebszyklus','Aminosäuren','Dysbiose'], keywords:['organische säuren','mitochondrien','energiestoffwechsel','krebs-zyklus','dysbiose','oxidativer stress'], description:'30+ organische Säuren aus Urin – tiefster Einblick in Mitochondrien und Stoffwechsel.', biomarker_names:['Pyruvat','Laktat','3-Hydroxybutyrat','Zitrat','α-Ketoglutarat','Fumarat','Malat','Succinat','Methylzitrat','Methylmalonsäure','Kynurensäure','Quinolinsäure','8-OHdG (DNA-Schaden)','Nitrophenylessigsäure','Citrullin','Kreatinin'] },
  { id:'cortisol-tagesprofil', name:'Cortisol-Tagesprofil', price:'89,00 €', sub:'4 Messzeitpunkte · Speichel · Heimtest', sample:'Speichel (4× täglich)', shop_slug:'cortisol-tagesprofil', cat:'Hormone & Stress', cat_key:'hormone', tags:['Cortisol','DHEA','HPA-Achse','Burnout','Stress'], keywords:['cortisol','dhea','tagesprofil','burnout','stress','hpa','nebenniere'], description:'Cortisol an 4 Tageszeitpunkten + DHEA – zeigt Erschöpfungsmuster und HPA-Dysregulation.', biomarker_names:['Cortisol (morgens)','Cortisol (mittags)','Cortisol (abends)','DHEA'] },
  { id:'hormonprofil-frau', name:'Frauen Hormonprofil', price:'129,00 €', sub:'5 Hormone · Speichel · Heimtest', sample:'Speichel', shop_slug:'hormonprofil-frau', cat:'Hormone & Stress', cat_key:'hormone', tags:['Östrogen','Progesteron','Testosteron','Cortisol','DHEA'], keywords:['frau','hormonprofil','östrogen','estradiol','progesteron','testosteron','cortisol','dhea','pms','menopause'], description:'5 Hormone aus Speichel – Zyklusstörungen, PMS, Wechseljahre, Libidoverlust.', biomarker_names:['Estradiol (E2)','Progesteron','Testosteron','Cortisol','DHEA'] },
  { id:'mann-hormonprofil-test', name:'Mann Hormonprofil', price:'129,00 €', sub:'5 Hormone · Speichel · Heimtest', sample:'Speichel', shop_slug:'mann-hormonprofil-test', cat:'Hormone & Stress', cat_key:'hormone', tags:['Testosteron','Estradiol','Progesteron','Cortisol','DHEA'], keywords:['mann','hormonprofil','testosteron','estradiol','progesteron','cortisol','dhea','libido','muskelabbau'], description:'5 Hormone aus Speichel – Testosteronmangel, Libidoverlust, Muskelabbau.', biomarker_names:['Testosteron','Estradiol (E2)','Progesteron','Cortisol','DHEA'] },
  { id:'melatonin', name:'Melatonin', price:'59,00 €', sub:'1 Parameter · Speichel · Heimtest', sample:'Speichel (nachts)', shop_slug:'melatonin', cat:'Hormone & Stress', cat_key:'hormone', tags:['Melatonin','Schlaf','Zirbeldrüse','Circadianer Rhythmus'], keywords:['melatonin','schlaf','schlafstörung','zirbeldrüse','circadian','schlafhormon'], description:'Melatonin aus Nacht-Speichel – Schlafhormon-Status und Zirbeldrüsenfunktion.', biomarker_names:['Melatonin (Nachtspeichel)'] },
  { id:'stress-erschoepfung-test', name:'Stress- & Erschöpfungs-Test', price:'175,00 €', sub:'6 Neurotransmitter + Stressprofil · Urin + Speichel', sample:'Urin + Speichel', shop_slug:'der-stress-erschopfung-test-neurotransmitter-diagnostik-gesund-alter-werden', cat:'Hormone & Stress', cat_key:'hormone', tags:['Cortisol','Neurotransmitter','Burnout','Erschöpfung','DHEA'], keywords:['stress','erschöpfung','burnout','neurotransmitter','cortisol','dhea','adrenalin'], description:'Umfassende Stressdiagnostik: 6 Neurotransmitter + Cortisol-Profil + DHEA.', biomarker_names:['Adrenalin','Noradrenalin','Dopamin','Serotonin','Glutamat','GABA'] },
  { id:'omega-3-test-fettsaure-analyse', name:'Omega-3/6 Fettsäure-Analyse', price:'89,00 €', sub:'8 Fettsäuren · Kapillarblut · Heimtest', sample:'Kapillarblut', shop_slug:'omega-3-test-fettsaure-analyse', cat:'Vitamine & Nährstoffe', cat_key:'vitamine', tags:['EPA','DHA','Omega-3','Omega-6','Entzündung','Herz'], keywords:['omega-3','omega-6','epa','dha','fettsäuren','entzündung','herzgesundheit'], description:'EPA, DHA, ALA und Omega-6/3-Quotient aus roten Blutzellen.', biomarker_names:['EPA','DHA','ALA','Linolsäure','Arachidonsäure','Omega-6/3-Quotient','EPA/AA-Quotient','Transfettsäuren'] },
  { id:'zellstressprofil', name:'Zellstressprofil – Nitrosativer Stress', price:'125,00 €', sub:'5 Parameter · Urin · Heimtest', sample:'Urin', shop_slug:'zellstressprofil', cat:'Stoffwechsel', cat_key:'stoff', tags:['8-OHdG','DNA-Schaden','Oxidativer Stress','Nitrosativer Stress','Mitochondrien'], keywords:['zellstress','8-ohdg','dna','oxidativer stress','nitrosativer stress','mitochondrien'], description:'5 Zellstress-Marker aus Urin – DNA-Schaden, Mitochondrienfunktion und NO-Stoffwechsel.', biomarker_names:['8-OHdG (DNA-Schaden)','4-Hydroxynitrophenyl-Essigsäure','Methylmalonsäure (MMA)','Citrullin','Kreatinin'] },
  { id:'jod-1', name:'Jod-Test', price:'39,00 €', sub:'1 Parameter · Urin · Heimtest', sample:'Urin (Morgenurin)', shop_slug:'jod-1', cat:'Mineralstoffe', cat_key:'mineralstoffe', tags:['Jod','Schilddrüse','Iodmangel'], keywords:['jod','iod','jodmangel','schilddrüse','jodstatus','urin'], description:'Jodausscheidung im Morgenurin – Jodspiegel und Schilddrüsenversorgung.', biomarker_names:['Jod gesamt (Urin)'] },
  { id:'darmmikrobiom-analyse', name:'Darmprofil Mikrobiom & Leaky-Gut', price:'315,00 €', sub:'Umfassendes Profil · Stuhl · Heimtest', sample:'Stuhl (Dreifachentnahme)', shop_slug:'darmmikrobiom-analyse-stuhltest-basisprofil', cat:'Darm & Verdauung', cat_key:'darm', tags:['Mikrobiom','Leaky-Gut','Zonulin','Dysbiose','IgA'], keywords:['mikrobiom','darm','stuhl','leaky-gut','zonulin','iga','akkermansia','candida','dysbiose'], description:'Umfassende Stuhlanalyse: Mikrobiom, Darmbarriere, Entzündungsmarker.', biomarker_names:['Lactobacillus','Bifidobacterium','Akkermansia muciniphila','Candida','Pathogene Keime','Pankreas-Enzymaktivität','Sekretorisches IgA','Zonulin','Histamin (Stuhl)'] },
  { id:'histamin-dao-analyse', name:'Histamin- & DAO-Enzym Analyse', price:'93,00 €', sub:'2 Parameter · Blut & Stuhl · Heimtest', sample:'Kapillarblut + Stuhl', shop_slug:'histamin-und-dao-enzym-analyse', cat:'Darm & Verdauung', cat_key:'darm', tags:['Histamin','DAO','Histaminintoleranz','Unverträglichkeit'], keywords:['histamin','histaminintoleranz','dao','diaminoxidase','stuhl','blut','unverträglichkeit'], description:'DAO-Enzymaktivität + intestinales Histamin – Histaminintoleranz-Diagnose.', biomarker_names:['DAO (Diaminoxidase)','Histamin (Stuhl)'] },
  { id:'darmgesundheit-check-up', name:'Darmgesundheit & Verdauungs-Check-up', price:'1.240,00 €', sub:'Komplett-Paket · Stuhl + Atemtest · Heimtest', sample:'Stuhl (Dreifachentnahme) + Atemgas', shop_slug:'darmgesundheit-verdauungs-check-up', cat:'Darm & Verdauung', cat_key:'darm', tags:['Mikrobiom','SIBO','Parasiten','Leaky-Gut','Zonulin','Calprotectin'], keywords:['darm','verdauung','mikrobiom','sibo','parasiten','leaky gut','zonulin','calprotectin','iga','histamin'], description:'Das umfassendste ORY-Darmpaket: Mikrobiom, SIBO, Parasiten, Zonulin, Calprotectin, Histamin, Neurotransmitter.', biomarker_names:['Mikrobiom-Komposition','Hefen & Pilze','Parasiten (PCR)','Zonulin','Calprotectin','Sekretorisches IgA','Pankreatische Elastase','Gallensäuren','SIBO (H₂/CH₄)','Histamin (Stuhl)','Tryptophan','Serotonin (Stuhl)','GABA (Stuhl)'] },
  { id:'longevity-check-up', name:'Gesundheits- & Longevity-Check-up', price:'1.521,98 €', sub:'75+ Parameter · Blut + Stuhl + Speichel + Urin · Heimtest', sample:'Kapillarblut + Stuhl + Speichel + Urin', shop_slug:'gesundheits-longevity-check-up', cat:'Komplex-Profile', cat_key:'komplex', tags:['Longevity','Prävention','Anti-Aging','NAD','Hormone','Mikrobiom'], keywords:['longevity','anti-aging','prävention','hormone','mikrobiom','nad','aminosäuren','testosteron'], description:'75+ Parameter: Aminosäuren, Vitamine, Cortisol, DHEA, Hormone, Mikrobiom, NAD, DNA-Stabilität.', biomarker_names:['Aminosäuren (Komplett)','EPA','DHA','Vitamin D3','Zink','Magnesium','Eisen','Cortisol (Profil)','DHEA','Entzündungsmarker','Gallensäuren','NAD','Mikrobiom','Testosteron','Estradiol','Progesteron','8-OHdG (DNA-Schaden)'] },
  { id:'schlaf-stress-paket', name:'Schlafprobleme & Stress-Diagnostik Paket', price:'762,00 €', sub:'Kombi-Paket · Speichel + Urin + Blut · Heimtest', sample:'Speichel (4x) + Urin + Kapillarblut', shop_slug:'schlaf-stress-problem-diagnostik-paket', cat:'Hormone & Stress', cat_key:'hormone', tags:['Schlaf','Cortisol','Melatonin','Neurotransmitter','Zellstress','DHEA'], keywords:['schlaf','stress','cortisol','melatonin','neurotransmitter','8-ohdg','dhea','erschöpfung','burnout'], description:'Schlaf- und Stressdiagnostik: Cortisol-Profil, Melatonin, Neurotransmitter, Zellstress, DNA-Stabilität.', biomarker_names:['8-OHdG (DNA-Schaden)','Oxidativer Stress','Nitrosativer Stress','Cortisol (morgens)','Cortisol (mittags)','Cortisol (abends)','DHEA','Melatonin','Adrenalin','Noradrenalin','Dopamin','Serotonin','GABA'] },
  { id:'helicobacter-pylori', name:'Helicobacter pylori Stuhltest', price:'65,00 €', sub:'1 Parameter · Stuhl · Heimtest', sample:'Stuhl (Einfachentnahme)', shop_slug:'helicobacter-pylori-stuhltest-fur-zuhause-ory-analysis', cat:'Darm & Verdauung', cat_key:'darm', tags:['H. pylori','Magengeschwür','Gastritis'], keywords:['helicobacter','h. pylori','magenbeschwerden','magengeschwür','gastritis','antigen','stuhltest'], description:'Heimtest zur Erkennung von Helicobacter pylori – häufigster bakterieller Magen-Erreger.', biomarker_names:['Helicobacter pylori-Antigen (Stuhl)'] },
  { id:'mikrobolom', name:'Mikrobolom – Mikrobiom & Neurotransmitter', price:'380,00 €', sub:'Molekulargenetische Analyse · Stuhl · Heimtest', sample:'Stuhl (Dreifachentnahme)', shop_slug:'mikrobolom-mikrobiom-neurotransmitter', cat:'Darm & Verdauung', cat_key:'darm', tags:['Mikrobiom','Neurotransmitter','Darm-Hirn-Achse','Dysbiose','Metabolom'], keywords:['mikrobolom','mikrobiom','neurotransmitter','darm-hirn-achse','metabolom','gallensäuren'], description:'Molekulargenetische Vollanalyse des Mikrobioms inkl. Neurotransmitter-Signale und Metabolom.', biomarker_names:['Mikrobiom-Diversität (16S-rRNA)','Funktionelle Bakteriengruppen','Metabolom','Neurotransmitter (intestinal)','Immunfunktion (IgA)','Barrierefunktion','Gallensäure-Metabolismus','Toxine (LPS)','Hefen (Candida)','Parasiten-Screening'] },
  { id:'colosafe', name:'Colosafe – Epigenetischer Darmvorsorge-Test', price:'275,00 €', sub:'1 Epigenetik-Marker · Stuhl · Heimtest', sample:'Stuhl', shop_slug:'colosafe', cat:'Darm & Verdauung', cat_key:'darm', tags:['Darmvorsorge','Epigenetik','Syndecan-2','Darmkrebs'], keywords:['colosafe','darmvorsorge','darmkrebs','syndecan-2','methylierung','früherkennung'], description:'Epigenetischer Stuhltest zur Früherkennung von Darmkrebs. 93,7% Übereinstimmung mit Koloskopie.', biomarker_names:['Syndecan-2-Methylierung (epigenetisch)'] },
  { id:'hautgesundheit-basis', name:'Hautgesundheit-Basis', price:'255,50 €', sub:'Haut-Darm-Hormon-Achse · Blut + Stuhl + Speichel', sample:'Kapillarblut + Stuhl + Speichel', shop_slug:'hautgesundheit-basis', cat:'Komplex-Profile', cat_key:'komplex', tags:['Haut','Akne','Mikrobiom','Hormone','Zink','Testosteron'], keywords:['haut','hautgesundheit','akne','mikrobiom','hormone','zink','testosteron','dysbiose'], description:'Haut-Darm-Hormon-Achse: Mikrobiom, Mineral- und Hormonanalytik für Hautprobleme.', biomarker_names:['Bakterielle Diversität (Mikrobiom)','Dysbiose-Index','Butyrat-produzierende Bakterien','Pilze (Candida)','Zink','Magnesium','Kupfer','Eisen','Calcium','Selen','Testosteron (Speichel)'] },
  { id:'vaginalflora', name:'Vaginalflora mit Aromatogramm', price:'193,21 €', sub:'Vaginale Mikrobiomanalyse · Abstrich · Heimtest', sample:'Vaginalabstrich', shop_slug:'vaginalflora-mit-aromatogramm', cat:'Darm & Verdauung', cat_key:'darm', tags:['Vaginalflora','Lactobacillus','Candida','Gardnerella','Aromatogramm'], keywords:['vaginalflora','lactobacillus','candida','gardnerella','aromatogramm','frauengesundheit'], description:'Vaginale Mikrobiomanalyse + Aromatogramm für gezielte Naturtherapie.', biomarker_names:['Vaginalflora-Komposition','Lactobacillus-Arten','Gardnerella vaginalis','Trichomonas vaginalis','Candida spp.','Enterococcus faecalis','Aromatogramm (ätherische Öle)'] },
  { id:'profil-parasiten-pcr', name:'Profil Parasiten PCR', price:'150,50 €', sub:'6 Parasiten (PCR) · Stuhl · Heimtest', sample:'Stuhl (Dreifachentnahme)', shop_slug:'profil-parasiten-pcr', cat:'Darm & Verdauung', cat_key:'darm', tags:['Parasiten','PCR','Giardia','Blastocystis','Cryptosporidium'], keywords:['parasiten','giardia','blastocystis','dientamoeba','entamoeba','cryptosporidium','pcr','stuhl'], description:'6 pathogene Darmparasiten per Multiplex-PCR – höchste Präzision.', biomarker_names:['Blastocystis hominis (PCR)','Giardia lamblia (PCR)','Dientamoeba fragilis (PCR)','Entamoeba histolytica (PCR)','Cryptosporidium spp. (PCR)','Cyclospora cayetanensis (PCR)'] },
  { id:'tryptophan-metabolismus', name:'Tryptophan-Metabolismus Test Plus', price:'375,00 €', sub:'10+ Parameter · Urin · Heimtest', sample:'Urin (Morgenurin)', shop_slug:'tryptophan-metabolismus-test-plus', cat:'Neurotransmitter', cat_key:'neuro', tags:['Tryptophan','Kynurenin','NAD','Serotonin','IDO','Quinolinsäure'], keywords:['tryptophan','kynurenin','nad','serotonin','ido','quinolinsäure','depression','schlaf'], description:'Tryptophan-Stoffwechselwege: Kynurenin-Weg, NAD-Synthese, IDO/KMO-Aktivität.', biomarker_names:['Tryptophan','Kynurenin','Kynurensäure','3-OH-Kynurenin','Quinolinsäure','NAD','Serotonin','Catecholamine','IDO-Aktivitätsindex','KMO-Aktivitätsindex','Kreatinin (Referenz)'] },
  { id:'beta-glucuronidase', name:'ß-Glucuronidase-Test', price:'45,00 €', sub:'1 Enzym-Parameter · Stuhl · Heimtest', sample:'Stuhl', shop_slug:'b-glucuronidase-test-fuer-zuhause-haus-chirurgie-betrag', cat:'Darm & Verdauung', cat_key:'darm', tags:['ß-Glucuronidase','Östrogen','Detox','Mikrobiom'], keywords:['beta-glucuronidase','glucuronidase','östrogen','detox','leber','hormone'], description:'ß-Glucuronidase-Aktivität im Stuhl – entscheidend für Hormonbalance und Detoxifikation.', biomarker_names:['ß-Glucuronidase-Aktivität (Stuhl)'] },
  { id:'coloalert', name:'ColoAlert – Darmkrebsfrüherkennung', price:'250,00 €', sub:'Okkultes Blut + Tumor-DNA · Stuhl · Heimtest', sample:'Stuhl', shop_slug:'coloalert-darmkrebsfrueherkennung-zu-hause', cat:'Darm & Verdauung', cat_key:'darm', tags:['Darmkrebs','KRAS','BRAF','Okkultes Blut','Tumor-DNA'], keywords:['coloalert','darmkrebs','kras','braf','tumor-dna','okkultes blut','früherkennung'], description:'Darmkrebsfrüherkennung: okkultes Blut + KRAS/BRAF-Mutationen. Sensitivität 85–90%.', biomarker_names:['Okkultes Blut (Hämoglobin)','KRAS-Mutation (DNA)','BRAF-Mutation (DNA)','Human-DNA (hDNA)'] },
];

// ─── BIOMARKERS DATA ────────────────────────────────────────────
const BIOMARKERS = [
  { slug:'dopamin', name:'Dopamin', aliases:['dopamin','dopamine','dopa'], description:'Dopamin ist der Neurotransmitter für Motivation, Antrieb und Belohnung. Wird aus Tyrosin über DOPA synthetisiert – abhängig von B6, Eisen und BH4.', symptoms:['Antriebslosigkeit','Prokrastination','ADHS','Belohnungssuche','Freudlosigkeit','Konzentrationsprobleme'], cofaktoren:[{name:'Vitamin B6 (P5P)',why:'Cofaktor der DOPA-Decarboxylase – ohne B6 kein Dopamin aus L-DOPA.'},{name:'Eisen',why:'Cofaktor der Tyrosinhydroxylase (Schlüsselenzym der Dopamin-Synthese).'},{name:'Zink',why:'Moduliert Dopamin-Rezeptoren und -Freisetzung.'}] },
  { slug:'serotonin', name:'Serotonin', aliases:['serotonin','5-htp','5-ht'], description:'Serotonin reguliert Stimmung, Schlaf, Appetit und soziales Verhalten. 95% wird im Darm produziert. Tryptophan ist der einzige Vorläufer.', symptoms:['Depression','Stimmungsschwankungen','Schlafstörung','Angst','Heißhunger auf Süßes','Reizbarkeit'], cofaktoren:[{name:'Tryptophan',why:'Einzige Vorstufe für Serotonin-Synthese.'},{name:'Vitamin B6',why:'Cofaktor der aromatischen Aminosäure-Decarboxylase.'},{name:'Magnesium',why:'Cofaktor der Tryptophan-Hydroxylase.'}] },
  { slug:'gaba', name:'GABA', aliases:['gaba','gamma-aminobuttersäure','gabapentin'], description:'GABA ist der wichtigste hemmende Neurotransmitter. Beruhigt das Nervensystem, fördert Schlaf und reduziert Angst. Glutamat ist der direkte Vorläufer.', symptoms:['Innere Unruhe','Angststörung','Einschlafprobleme','Übererregbarkeit','Burnout','Muskelverspannung'], cofaktoren:[{name:'Vitamin B6 (P5P)',why:'Cofaktor der Glutamat-Decarboxylase (GAD) – konvertiert Glutamat zu GABA.'},{name:'Magnesium',why:'Moduliert GABA-A-Rezeptoren.'},{name:'Taurin',why:'Potenziert GABA-Wirkung an Rezeptoren.'}] },
  { slug:'adrenalin', name:'Adrenalin', aliases:['adrenalin','epinephrin','epinephrine'], description:'Adrenalin ist das Stresshormon der Nebenniere. Aktiviert im Notfall Herzfrequenz, Blutdruck und Energiemobilisierung.', symptoms:['Erschöpfung bei Stress','Herzrasen','Kalte Hände/Füße','Schlafstörung','Burnout','Panikattacken'], cofaktoren:[{name:'Vitamin C',why:'Cofaktor der Dopamin-β-Hydroxylase.'},{name:'Kupfer',why:'Cofaktor der Dopamin-β-Hydroxylase.'}] },
  { slug:'noradrenalin', name:'Noradrenalin', aliases:['noradrenalin','norepinephrin','norepinephrine'], description:'Noradrenalin steuert Aufmerksamkeit, Konzentration und Blutdruck. Zusammen mit Dopamin reguliert es den präfrontalen Cortex.', symptoms:['Brain Fog','Konzentrationsprobleme','Antriebsmangel','Chronischer Stress','ADHS','Schlafstörung'], cofaktoren:[{name:'Vitamin B6',why:'Cofaktor der Biosynthese.'},{name:'Kupfer',why:'Cofaktor der Dopamin-β-Hydroxylase.'}] },
  { slug:'cortisol', name:'Cortisol', aliases:['cortisol','kortisol','stresshormon','hydrocortison'], description:'Cortisol ist das Hauptstresshormon der Nebennierenrinde. Reguliert Immunsystem, Entzündung, Blutzucker und Schlaf-Wach-Rhythmus.', symptoms:['Erschöpfung morgens','Abends wach','Gewichtszunahme Bauch','Schlafstörung','Infektanfälligkeit','Burnout'], cofaktoren:[{name:'Vitamin C',why:'Höchste Konzentration in der Nebenniere – direkte Unterstützung der Cortisol-Synthese.'},{name:'Magnesium',why:'Puffert Cortisol-induzierte Kalzium-Überladung der Zellen.'}] },
  { slug:'dhea', name:'DHEA', aliases:['dhea','dehydroepiandrosteron','dheas'], description:'DHEA ist ein Nebennierenhormon und Vorläufer von Testosteron und Östrogen. Wichtigster Anti-Aging-Marker der Nebennierenreserve.', symptoms:['Erschöpfung','Libidoverlust','Immunschwäche','Muskelabbau','Depression','Kognitive Abnahme'], cofaktoren:[{name:'Vitamin D',why:'Stimuliert DHEA-Synthese.'},{name:'Zink',why:'Cofaktor der Steroidhormonsynthese.'}] },
  { slug:'vitamin-d', name:'Vitamin D', aliases:['vitamin d','vitamin d3','25-oh-d','cholecalciferol','d3'], description:'Vitamin D ist ein Prohormon das Immunsystem, Knochen, Muskel und Nervensystem steuert. 80% der Deutschen sind mangelhaft versorgt.', symptoms:['Erschöpfung','Infektanfälligkeit','Knochenschmerzen','Depression','Muskelkrämpfe','Haarausfall'], cofaktoren:[{name:'Vitamin K2',why:'Lenkt Calcium in Knochen statt Arterien.'},{name:'Magnesium',why:'Cofaktor aller Vitamin-D-aktivierenden Enzyme.'}] },
  { slug:'vitamin-b12', name:'Vitamin B12', aliases:['vitamin b12','b12','cobalamin','methylcobalamin','adenosylcobalamin'], description:'B12 ist essenziell für Nervensystem, DNA-Synthese und Methylierungszyklus. Mangel schleicht sich über Jahre ein – häufig bei Vegetariern.', symptoms:['Erschöpfung','Kribbeln / Taubheit','Brain Fog','Vergesslichkeit','Anämie','Stimmungstief'], cofaktoren:[{name:'Folsäure',why:'B12 und Folat arbeiten im Methylierungszyklus zusammen.'},{name:'Intrinsic Factor',why:'Magenprotein für B12-Aufnahme – bei Mangel direkte Injektion nötig.'}] },
  { slug:'magnesium', name:'Magnesium', aliases:['magnesium','mg','magnesium malat','magnesium glycinat'], description:'Magnesium ist Cofaktor von über 300 Enzymen. Essenziell für Energie (ATP), Muskelentspannung, Schlaf und Nervenfunktion.', symptoms:['Muskelkrämpfe','Schlafprobleme','Herzrasen','Kopfschmerzen','Erschöpfung','Innere Unruhe'], cofaktoren:[{name:'Vitamin D',why:'Cofaktor aller Vitamin-D-Enzyme – Mangel blockiert Vitamin-D-Aktivierung.'},{name:'Vitamin B6',why:'Synergistisch: beide fördern Magnesium-Eintritt in die Zelle.'}] },
  { slug:'zink', name:'Zink', aliases:['zink','zinc','zn'], description:'Zink ist Cofaktor von 300+ Enzymen. Kritisch für Immunsystem, Wundheilung, Hormonproduktion und DNA-Synthese.', symptoms:['Häufige Infekte','Haarausfall','Wundheilungsstörung','Hormonmangel','Geschmacksverlust','Akne'], cofaktoren:[{name:'Kupfer',why:'Kupfer-Zink-Ratio ist wichtiger Entzündungsmarker.'},{name:'Vitamin A',why:'Zink aktiviert Retinol-Bindungsprotein für Vitamin-A-Transport.'}] },
  { slug:'selen', name:'Selen', aliases:['selen','selenium','se','selenomethionin'], description:'Selen ist essenziell für Schilddrüsenhormone (Dejodase), Glutathion-Peroxidase (Antioxidans) und Immunfunktion.', symptoms:['Schilddrüsenprobleme','Erschöpfung','Immunschwäche','Muskelschmerzen','Haarausfall','Herzprobleme'], cofaktoren:[{name:'Vitamin E',why:'Selen (GPX) und Vitamin E schützen synergistisch vor Lipidperoxidation.'},{name:'Jod',why:'Selen-Dejodase aktiviert Schilddrüsenhormon T4→T3.'}] },
  { slug:'eisen', name:'Eisen / Ferritin', aliases:['eisen','ferritin','hämoglobin','fe','iron','serumeisen'], description:'Eisen ist essenziell für Sauerstofftransport (Hämoglobin), Energiestoffwechsel und Neurotransmitter-Synthese. Ferritin ist der Speicherwert.', symptoms:['Haarausfall','Erschöpfung','Blässe','Restless Legs','Konzentrationsprobleme','Kurzatmigkeit'], cofaktoren:[{name:'Vitamin C',why:'Erhöht Eisen-Resorption im Dünndarm um bis zu 300%.'},{name:'Vitamin B12 + Folsäure',why:'Werden für Blutbildung (Erythropoese) zusammen mit Eisen benötigt.'}] },
  { slug:'histamin', name:'Histamin / DAO', aliases:['histamin','histamine','dao','diaminoxidase','histaminintoleranz'], description:'Histamin ist ein biogenes Amin. Bei Histaminunverträglichkeit fehlt das Abbauenzym DAO – Histamin aus Nahrung akkumuliert.', symptoms:['Kopfschmerzen nach Essen','Flush / Rötung','Herzrasen','Blähungen','Juckreiz','Schnupfen','Histaminunverträglichkeit','Nahrungsmittelreaktion'], cofaktoren:[{name:'Vitamin B6 (P5P)',why:'Cofaktor von DAO.'},{name:'Kupfer',why:'Cofaktor von DAO.'}] },
  { slug:'omega-3', name:'Omega-3 (EPA/DHA)', aliases:['omega-3','omega 3','epa','dha','fischöl','fettsäuren'], description:'EPA und DHA sind entzündungshemmende Fettsäuren. Der Omega-3-Index (EPA+DHA in Erythrozyten) ist wichtigster Herzmarker.', symptoms:['Herzerkrankung','Entzündungen','Depression','Brain Fog','trockene Haut','Gelenkschmerzen'], cofaktoren:[{name:'Vitamin E',why:'Schützt EPA/DHA vor Oxidation.'},{name:'Magnesium',why:'Synergistisch kardioprotetkiv.'}] },
  { slug:'tryptophan', name:'Tryptophan', aliases:['tryptophan','l-tryptophan','trp'], description:'Tryptophan ist die einzige Vorstufe für Serotonin und Melatonin. Wird über Kynurenin-Weg (95%) oder Serotonin-Weg (5%) metabolisiert.', symptoms:['Depression','Schlafstörung','Brain Fog','Erschöpfung','Angst','Chronische Entzündung'], cofaktoren:[{name:'Vitamin B6',why:'Cofaktor der Tryptophan-Hydroxylase.'},{name:'Magnesium',why:'Moduliert IDO-Aktivität.'}] },
  { slug:'vitamin-b6', name:'Vitamin B6', aliases:['vitamin b6','b6','pyridoxin','p5p','pyridoxal-5-phosphat'], description:'Vitamin B6 (P5P) ist Cofaktor von 160+ Enzymen: Neurotransmitter-Synthese, Hormonstoffwechsel, Immunfunktion und Methylierung.', symptoms:['Reizbarkeit','Schlafstörungen','PMS','Periphere Neuropathie','Depressive Stimmung','Tunnelkarpalsyndrom'], cofaktoren:[{name:'Magnesium',why:'Synergistisch für Nervensystem.'},{name:'Riboflavin (B2)',why:'Riboflavin aktiviert B6 in seine aktive Form P5P.'}] },
  { slug:'folsaeure', name:'Folsäure', aliases:['folsäure','folat','b9','vitamin b9','mthfr','methylfolat'], description:'Folsäure (B9) ist essenziell für Zellteilung, DNA-Synthese und Methylierungszyklus. Zusammen mit B12 reguliert sie Homocystein.', symptoms:['Anämie','Erschöpfung','Erhöhtes Homocystein','Konzentrationsprobleme','Depressive Verstimmung','Schwangerschaftskomplikationen'], cofaktoren:[{name:'Vitamin B12',why:'B12 und Folat arbeiten im Methylierungszyklus zusammen.'},{name:'Vitamin B6',why:'Bilden das Homocystein-Dreigestirn.'}] },
  { slug:'melatonin', name:'Melatonin', aliases:['melatonin','schlafhormon','zirbeldrüse'], description:'Melatonin ist das Schlafhormon der Zirbeldrüse. Reguliert den circadianen Rhythmus, schützt Mitochondrien und wirkt antioxidativ.', symptoms:['Schlafstörung','Einschlafprobleme','Durchschlafprobleme','Tagesmüdigkeit','Jetlag','Winterdepression'], cofaktoren:[{name:'Tryptophan → Serotonin',why:'Melatonin wird aus Serotonin synthetisiert – Tryptophan ist Ausgangsstoff.'},{name:'Magnesium',why:'Cofaktor der HIOMT-Enzym (letzte Stufe Melatonin-Synthese).'}] },
  { slug:'vitamin-e', name:'Vitamin E (Tocopherol)', aliases:['vitamin e','tocopherol','alpha-tocopherol','vitamin-e'], description:'Vitamin E ist das wichtigste fettlösliche Antioxidans. Schützt Zellmembranen, Omega-3-Fettsäuren und LDL vor Oxidation.', symptoms:['Muskelschwäche','Nervenschäden','Immunschwäche','Unfruchtbarkeit','Sehstörungen','Erschöpfung'], cofaktoren:[{name:'Selen',why:'Synergistischer Antioxidansschutz über Glutathion-Peroxidase.'},{name:'Vitamin C',why:'Regeneriert oxidiertes Vitamin E.'}] },
  { slug:'coq10', name:'Coenzym Q10 (Ubiquinol)', aliases:['coq10','coenzym q10','ubiquinol','ubiquinon','q10'], description:'CoQ10 ist der Elektronencarrier in der mitochondrialen Atmungskette. Ohne CoQ10 kein ATP. Statine blockieren CoQ10-Synthese.', symptoms:['Erschöpfung','Muskelschwäche','Herzprobleme','Brain Fog','Muskelschmerzen unter Statinen'], cofaktoren:[{name:'Selen',why:'Selenoprotein Q ist CoQ10-Cofaktor.'},{name:'Vitamin B6',why:'Cofaktor der CoQ10-Biosynthese.'}] },
  { slug:'kupfer', name:'Kupfer', aliases:['kupfer','copper','cu','ceruloplasmin'], description:'Kupfer ist Cofaktor von Enzymen für Bindegewebe (Lysyloxidase), Eisentransport (Ceruloplasmin), Mitochondrien und Dopamin-Synthese.', symptoms:['Anämie','Erschöpfung','Osteoporose','Immunschwäche','Pigmentierungsstörungen','Nervenschäden'], cofaktoren:[{name:'Zink',why:'Kupfer-Zink-Ratio ist Entzündungsmarker. Zink hemmt Kupfer-Absorption.'},{name:'Vitamin C',why:'Cofaktor der Kupfer-abhängigen Enzyme.'}] },
  { slug:'calcium', name:'Calcium', aliases:['calcium','kalzium','ca','kalziumspiegel'], description:'Calcium ist der häufigste Mineralstoff im Körper. Essenziell für Knochen, Muskelkontraktion, Nervensignale und Blutgerinnung.', symptoms:['Muskelkrämpfe','Knochenschwäche','Kribbeln','Herzrhythmusstörungen','Schlafstörungen','Depressive Stimmung'], cofaktoren:[{name:'Vitamin D',why:'Reguliert Calcium-Resorption im Darm.'},{name:'Vitamin K2',why:'Lenkt Calcium in Knochen, nicht Arterien (MGP-Protein).'}] },
  { slug:'natrium-kalium', name:'Natrium & Kalium', aliases:['natrium','kalium','na','k','elektrolyte','kochsalz'], description:'Natrium und Kalium regulieren den Flüssigkeitshaushalt, Blutdruck und Nervenimpulse. Das Na/K-Verhältnis ist kritisch für Herzfunktion.', symptoms:['Bluthochdruck','Muskelkrämpfe','Herzrhythmusstörungen','Schwäche','Kopfschmerzen','Ödeme'], cofaktoren:[{name:'Magnesium',why:'Magnesium reguliert Na/K-ATPase – die "Pumpe" für Natrium-Kalium-Gleichgewicht.'}] },
  { slug:'tsh-schilddruese', name:'TSH / Schilddrüse', aliases:['tsh','schilddrüse','thyreoidea','t3','t4','thyroxin','hypothyreose','hyperthyreose'], description:'TSH steuert die Schilddrüse – den Stoffwechselregulator des Körpers. T4 wird zu aktivem T3 konvertiert. Jod und Selen sind essenziell.', symptoms:['Erschöpfung','Gewichtszunahme','Frieren','Haarausfall','Verstopfung','Depressive Stimmung','Trockene Haut','Bradykardie'], cofaktoren:[{name:'Jod',why:'Baustein von T3 und T4 – ohne Jod keine Schilddrüsenhormone.'},{name:'Selen',why:'Dejodase (T4→T3-Konversion) ist selenabhängig.'},{name:'Zink',why:'Cofaktor des T3-Rezeptors.'},{name:'Vitamin D',why:'Moduliert TSH-Rezeptor-Expression.'}] },
  { slug:'hscrp-entzuendung', name:'hsCRP / Entzündungsmarker', aliases:['hscrp','hs-crp','crp','entzündung','entzündungsmarker','inflammation'], description:'hsCRP (hochsensitives CRP) ist der sensitivste Marker für systemische Entzündung. Erhöhte Werte sind stärkster Prädiktor für Herzinfarktrisiko.', symptoms:['Chronische Erschöpfung','Gelenkschmerzen','Muskelschmerzen','Brain Fog','Häufige Infekte','Herzerkrankung'], cofaktoren:[{name:'Omega-3 (EPA/DHA)',why:'Senkt hsCRP durch Resolvine und Protektine.'},{name:'Vitamin D',why:'Hemmt NF-κB-Entzündungssignalweg.'},{name:'Curcumin',why:'Potenter NF-κB-Hemmer.'}] },
  { slug:'cholesterin-lipide', name:'Cholesterin & Lipide', aliases:['cholesterin','ldl','hdl','triglyzeride','lipide','gesamt-cholesterin','lipidprofil'], description:'Cholesterin ist Baustein aller Steroidhormone und Zellmembranen. LDL/HDL-Ratio und Triglyzeride zeigen kardiovaskuläres Risiko. Oxidiertes LDL ist das eigentlich Gefährliche.', symptoms:['Herzerkrankung','Schlaganfall','Atherosklerose','Gallensteine','Pankreatitis','Xanthome'], cofaktoren:[{name:'Omega-3',why:'Senkt Triglyzeride und erhöht HDL.'},{name:'CoQ10',why:'Schützt LDL vor Oxidation.'},{name:'Vitamin D',why:'Reguliert Cholesterin-Stoffwechsel in Leber.'}] },
  { slug:'homocystein', name:'Homocystein', aliases:['homocystein','homocysteine','hcy'], description:'Homocystein ist ein toxisches Zwischenprodukt des Methionin-Stoffwechsels. Erhöhte Werte schädigen Gefäßwände und erhöhen Herzinfarkt- und Demenzrisiko massiv.', symptoms:['Herzerkrankung','Demenz','Schlaganfall','Thrombose','Depression','Gedächtnisprobleme'], cofaktoren:[{name:'Vitamin B12',why:'B12, B6 und Folat sind die drei Enzyme die Homocystein abbbauen.'},{name:'Folsäure',why:'Direkter Homocystein-Senker.'},{name:'Vitamin B6',why:'Transsulfurierungsweg: B6 lenkt Homocystein in Cystein um.'}] },
  { slug:'jod', name:'Jod', aliases:['jod','iod','iodine','jodmangel'], description:'Jod ist der einzige Baustein der Schilddrüsenhormone T3 und T4. Deutschland ist klassisches Jodmangelgebiet. Jodmangel ist weltweit häufigste vermeidbare Ursache geistiger Entwicklungsstörungen.', symptoms:['Schilddrüsenunterfunktion','Erschöpfung','Gewichtszunahme','Struma','Kognitive Verlangsamung','Kältegefühl'], cofaktoren:[{name:'Selen',why:'Dejodase (T4→T3) ist selenabhängig – ohne Selen kein aktives Schilddrüsenhormon.'},{name:'Vitamin D',why:'Moduliert Jod-Aufnahme in Schilddrüsenzellen.'}] },
  { slug:'8-ohdg-zellstress', name:'8-OHdG / Zellstress', aliases:['8-ohdg','8-hydroxy-desoxyguanosin','dna-schaden','zellstress','oxidativer dna-schaden'], description:'8-OHdG ist ein direkter Marker für oxidativen DNA-Schaden. Erhöhte Werte zeigen beschleunigtes Altern, Krebsrisiko und Mitochondrien-Dysfunktion an.', symptoms:['Beschleunigtes Altern','Kognitive Abnahme','Erschöpfung','Entzündungsneigung','Herzerkrankung'], cofaktoren:[{name:'CoQ10',why:'Schützt mitochondriale DNA vor Oxidation.'},{name:'Alpha-Liponsäure',why:'Universalantioxidans – regeneriert Glutathion und Vitamin C.'},{name:'NAC (N-Acetylcystein)',why:'Steigert Glutathion-Spiegel – wichtigstes zelluläres Antioxidans.'}] },
  { slug:'igg-nahrungsmittel', name:'IgG-Antikörper / Nahrungsmittelunverträglichkeit', aliases:['igg','igg-antikörper','nahrungsmittelunverträglichkeit','food intolerance','lebensmittelunverträglichkeit'], description:'IgG-Antikörper entstehen bei verzögerter Immunreaktion auf Nahrungsmittel (6–72h nach Konsum). Sind bei Leaky Gut häufig erhöht – entzündungsfördernd und schwer zuzuordnen.', symptoms:['Nahrungsmittelunverträglichkeiten','Blähungen','Hautprobleme','Gelenkschmerzen','Brain Fog','Chronische Erschöpfung','Migräne'], cofaktoren:[{name:'Probiotika',why:'Reduzieren Darmpermeabilität.'},{name:'L-Glutamin',why:'Stärkt Darmbarriere.'}] },
  { slug:'gluten-zoeliakie', name:'Gluten / Gliadin / Zöliakie', aliases:['gluten','gliadin','zöliakie','transglutaminase','tg2','glutenunverträglichkeit','weizen'], description:'Gliadin-Antikörper (AGA) und Anti-TG2 zeigen Glutenunverträglichkeit und Zöliakie an. Zöliakie ist eine Autoimmunerkrankung – lebenslange Glutenvermeidung nötig. Nicht-zöliakische Glutensensitivität ebenfalls häufig.', symptoms:['Blähungen','Durchfall','Bauchschmerzen','Erschöpfung','Gewichtsverlust','Anämie','Dermatitis herpetiformis'], cofaktoren:[{name:'Zink',why:'Zöliakie verursacht Zinkmangel durch Malabsorption.'},{name:'Vitamin D',why:'Häufig mangelversorgt bei Zöliakie durch Malabsorption.'}] },
  { slug:'laktose', name:'Laktose / Laktasemangel', aliases:['laktose','milchzucker','laktase','laktoseintoleranz','lactose'], description:'Laktasemangel (kongenital oder sekundär nach Darmentzündung) führt dazu dass Milchzucker nicht gespalten wird → Fermentation im Dickdarm → H₂ → Blähungen, Krämpfe, Durchfall.', symptoms:['Blähungen nach Milchprodukten','Bauchkrämpfe','Durchfall','Übelkeit','Bauchschmerzen'], cofaktoren:[{name:'Probiotika (Lactobacillus acidophilus)',why:'Produzieren Laktase und verbessern Laktose-Toleranz.'},{name:'Laktase-Enzyme',why:'Enzym-Supplementation kompensiert Laktasemangel direkt.'}] },
  { slug:'mikrobiom', name:'Mikrobiom & Darmflora', aliases:['mikrobiom','darmflora','darmbakterien','mikrobiota','darm','leaky gut','dysbiose'], description:'Das Darmmikrobiom beeinflusst Immunsystem, Stimmung, Gewicht und Energie. Dysbiosen verursachen Blähungen, Verstopfung, systemische Entzündung über Leaky Gut.', symptoms:['Blähungen','Verstopfung','Durchfall','Bauchschmerzen','Reizdarm','Erschöpfung nach Essen','Nahrungsmittelunverträglichkeiten','Gewichtszunahme'], cofaktoren:[{name:'Probiotika',why:'Direkte Wiederherstellung der Darmflora.'},{name:'L-Glutamin',why:'Stärkt Tight Junctions.'}] },
  { slug:'verdauungsenzyme-sibo', name:'Verdauungsenzyme & SIBO', aliases:['sibo','verdauungsenzyme','reizdarm','ibs','motilität','obstipation'], description:'SIBO ist eine Fehlbesiedelung des Dünndarms. Methan-SIBO verlangsamt Darmmotilität → Verstopfung. H₂-SIBO → Durchfall, Blähungen.', symptoms:['Verstopfung','Blähungen','Bauchkrämpfe','Reizdarm','Durchfall','Erschöpfung nach Essen'], cofaktoren:[{name:'Magnesium',why:'Fördert Peristaltik bei Verstopfung.'},{name:'Probiotika (L. reuteri)',why:'Reduziert Methan-Archaeen.'}] },
  { slug:'testosteron', name:'Testosteron', aliases:['testosteron','testosterone','freies testosteron','androgen'], description:'Testosteron reguliert Muskelmasse, Libido, Knochen und Stimmung. Chronischer Stress (Cortisol) ist der häufigste Testosteron-Killer.', symptoms:['Libidoverlust','Muskelabbau','Erschöpfung','Depressive Stimmung','Bauchfett','Erektionsprobleme','Antriebslosigkeit'], cofaktoren:[{name:'Zink',why:'Hemmt Aromatase (Testosteron→Östrogen).'},{name:'Vitamin D',why:'Testosteron-Synthese ist Vitamin-D-abhängig.'}] },
  { slug:'oestrogen', name:'Östrogen / Estradiol', aliases:['östrogen','estrogen','estradiol','e2','progesteron','progesterone'], description:'Estradiol reguliert Menstruationszyklus, Knochendichte, Stimmung. Östrogendominanz entsteht wenn Progesteron relativ zu niedrig ist.', symptoms:['PMS','Stimmungsschwankungen','Regelschmerzen','Schlafprobleme','Brustspannen','Hitzewallungen','Wechseljahresbeschwerden'], cofaktoren:[{name:'Vitamin B6',why:'Fördert Progesteron-Synthese.'},{name:'Magnesium',why:'Aktiviert COMT für Östrogen-Entgiftung.'}] },
  { slug:'helicobacter', name:'Helicobacter pylori', aliases:['helicobacter','h. pylori','hp','gastritis','magengeschwür'], description:'H. pylori besiedelt die Magenschleimhaut bei ~40% der Deutschen. Verursacht chronische Gastritis, Magengeschwüre und erhöht Magenkrebs-Risiko.', symptoms:['Magenschmerzen','Sodbrennen','Übelkeit','Völlegefühl','Blähungen','Appetitlosigkeit'], cofaktoren:[{name:'Probiotika (L. reuteri)',why:'Hemmt H. pylori-Adhäsion.'},{name:'Mastix',why:'Pflanzlich mit Anti-H.-pylori-Wirkung.'}] },
  { slug:'kynurenin-nad', name:'Kynurenin / NAD', aliases:['kynurenin','nad','nicotinamid','ido','quinolinsäure','tryptophan metabolismus'], description:'Der Kynurenin-Weg verarbeitet 95% des Tryptophans. Entzündung aktiviert IDO → weniger Serotonin, mehr neurotoxische Quinolinsäure. NAD ist der Energiecarrier der Mitochondrien.', symptoms:['Depressive Stimmung','Chronische Erschöpfung','Schlafstörung','Brain Fog','Neuroinflammation','Antriebsmangel'], cofaktoren:[{name:'Niacinamid (B3)',why:'Direkter NAD-Vorläufer.'},{name:'Curcumin',why:'Hemmt IDO-Aktivierung.'}] },
  { slug:'beta-glucuronidase', name:'ß-Glucuronidase', aliases:['beta-glucuronidase','glucuronidase','detox','enterohepatisch'], description:'ß-Glucuronidase reaktiviert dekonjugiertes Östrogen im Darm. Erhöhte Aktivität durch Dysbiose verursacht Östrogendominanz und erhöhtes Krebsrisiko.', symptoms:['PMS','Östrogendominanz','Brustspannen','Akne','Hormondysbalance','Erschöpfung'], cofaktoren:[{name:'Calcium-D-Glucarat',why:'Hemmt ß-Glucuronidase direkt.'},{name:'DIM',why:'Fördert schützende Östrogenmetabolite.'}] },
  { slug:'parasiten', name:'Parasiten (Darm)', aliases:['parasiten','giardia','blastocystis','dientamoeba','entamoeba','cryptosporidium','darmparasiten'], description:'Intestinale Parasiten werden oft als Reizdarm-Ursache übersehen. Blastocystis und Dientamoeba fragilis bei bis zu 30% der Reizdarm-Patienten.', symptoms:['Chronischer Durchfall','Blähungen','Bauchkrämpfe','Übelkeit','Erschöpfung','Reizdarm'], cofaktoren:[{name:'Artemisia annua',why:'Antiparasitäre Wirkung.'},{name:'Berberin',why:'Gegen Giardia, Blastocystis.'}] },
  { slug:'calprotectin', name:'Calprotectin / Darmwandentzündung', aliases:['calprotectin','calprotektin','darmwandentzündung','colitis','crohn'], description:'Calprotectin ist der sensitivste Marker für mukosale Darmentzündung. Differenziert zwischen entzündlicher Darmerkrankung und funktionellem Reizdarm.', symptoms:['Blut im Stuhl','Chronischer Durchfall','Bauchschmerzen','Gewichtsverlust','Erschöpfung','Gelenkentzündungen'], cofaktoren:[{name:'Curcumin',why:'Entzündungshemmend bei CED.'},{name:'Omega-3',why:'Senkt Calprotectin in Studien.'}] },
  { slug:'zonulin', name:'Zonulin / Leaky Gut', aliases:['zonulin','leaky gut','darmpermeabilität','tight junctions','darmbarriere'], description:'Zonulin reguliert Tight Junctions. Erhöhte Werte zeigen erhöhte Darmpermeabilität (Leaky Gut) – Voraussetzung für systemische Entzündung und Autoimmunerkrankungen.', symptoms:['Nahrungsmittelunverträglichkeiten','Blähungen','Brain Fog','Autoimmunerkrankung','Hautprobleme','Chronische Erschöpfung'], cofaktoren:[{name:'L-Glutamin',why:'Stärkt Tight Junctions.'},{name:'Vitamin D',why:'Reguliert Tight-Junction-Proteine.'}] },
];

// ─── MAPPING: welcher Biomarker in welchem Test (test_id, biomarker_slug, pct, note) ───
const MAPPINGS = [
  // Dopamin
  {t:'neurotransmitter-plus', b:'dopamin', pct:96, note:'Dopamin direkt im Urin gemessen.'},{t:'stress-erschoepfung-test', b:'dopamin', pct:92, note:'Dopamin im Stress-Profil.'},{t:'prevent-360', b:'dopamin', pct:80, note:'Neurotransmitter-Metabolite im 75-Parameter-Profil.'},{t:'schlaf-stress-paket', b:'dopamin', pct:88, note:'Dopamin im Schlaf-Stress-Paket.'},
  // Serotonin
  {t:'neurotransmitter-plus', b:'serotonin', pct:96, note:'Serotonin direkt gemessen.'},{t:'tryptophan-metabolismus', b:'serotonin', pct:90, note:'Serotonin als Teil des Tryptophan-Wegs.'},{t:'prevent-360', b:'serotonin', pct:78, note:'Serotonin-Metabolite im großen Profil.'},{t:'darmgesundheit-check-up', b:'serotonin', pct:72, note:'Serotonin (intestinal) im Darm-Paket.'},{t:'schlaf-stress-paket', b:'serotonin', pct:88, note:'Serotonin im Schlaf-Stress-Paket.'},{t:'mikrobolom', b:'serotonin', pct:68, note:'Serotonin-Signale im Mikrobolom.'},
  // GABA
  {t:'neurotransmitter-plus', b:'gaba', pct:96, note:'GABA direkt gemessen.'},{t:'prevent-360', b:'gaba', pct:80, note:'GABA im großen Profil.'},{t:'schlaf-stress-paket', b:'gaba', pct:88, note:'GABA im Schlaf-Stress-Paket.'},{t:'darmgesundheit-check-up', b:'gaba', pct:65, note:'GABA (intestinal) im Darm-Paket.'},
  // Adrenalin
  {t:'neurotransmitter-plus', b:'adrenalin', pct:96, note:'Adrenalin direkt.'},{t:'stress-erschoepfung-test', b:'adrenalin', pct:92, note:'Adrenalin im Stress-Profil.'},{t:'schlaf-stress-paket', b:'adrenalin', pct:88, note:'Adrenalin im Schlaf-Stress-Paket.'},
  // Noradrenalin
  {t:'neurotransmitter-plus', b:'noradrenalin', pct:96, note:'Noradrenalin direkt.'},{t:'stress-erschoepfung-test', b:'noradrenalin', pct:92, note:'Noradrenalin im Stress-Profil.'},{t:'schlaf-stress-paket', b:'noradrenalin', pct:88, note:'Noradrenalin im Schlaf-Stress-Paket.'},
  // Cortisol
  {t:'cortisol-tagesprofil', b:'cortisol', pct:97, note:'Cortisol an 4 Tageszeitpunkten – Goldstandard.'},{t:'schlaf-stress-paket', b:'cortisol', pct:94, note:'Cortisol-Tagesprofil im Schlaf-Stress-Paket.'},{t:'hormonprofil-frau', b:'cortisol', pct:85, note:'Cortisol im Frauen-Hormonprofil.'},{t:'mann-hormonprofil-test', b:'cortisol', pct:85, note:'Cortisol im Mann-Hormonprofil.'},{t:'stress-erschoepfung-test', b:'cortisol', pct:88, note:'Cortisol im Erschöpfungs-Test.'},{t:'prevent-360', b:'cortisol', pct:78, note:'Cortisol im 360-Profil.'},{t:'longevity-check-up', b:'cortisol', pct:90, note:'Cortisol im Longevity-Panel.'},
  // DHEA
  {t:'cortisol-tagesprofil', b:'dhea', pct:94, note:'DHEA als Nebennierenreserve-Marker.'},{t:'hormonprofil-frau', b:'dhea', pct:88, note:'DHEA im Frauen-Hormonprofil.'},{t:'mann-hormonprofil-test', b:'dhea', pct:88, note:'DHEA im Mann-Hormonprofil.'},{t:'schlaf-stress-paket', b:'dhea', pct:90, note:'DHEA im Stress-Schlaf-Paket.'},{t:'prevent-360', b:'dhea', pct:75, note:'DHEA im 360-Profil.'},{t:'longevity-check-up', b:'dhea', pct:88, note:'DHEA im Longevity-Panel.'},
  // Vitamin D
  {t:'vitamincheck-basis', b:'vitamin-d', pct:96, note:'Vitamin D3 (25-OH) direkt.'},{t:'om-vital', b:'vitamin-d', pct:92, note:'Vitamin D im OM-Vital-Panel.'},{t:'prevent-360', b:'vitamin-d', pct:88, note:'Vitamin D im 360-Profil.'},{t:'longevity-check-up', b:'vitamin-d', pct:90, note:'Vitamin D im Longevity-Panel.'},{t:'hautgesundheit-basis', b:'vitamin-d', pct:70, note:'Vitamin D indirekt über Mineralien.'},
  // Vitamin B12
  {t:'vitamincheck-basis', b:'vitamin-b12', pct:96, note:'B12 direkt.'},{t:'om-vital', b:'vitamin-b12', pct:92, note:'B12 im OM-Vital.'},{t:'prevent-360', b:'vitamin-b12', pct:88, note:'B12 im 360-Profil.'},
  // Magnesium
  {t:'vollblutmineralanalyse', b:'magnesium', pct:97, note:'Magnesium intrazellulär – aussagekräftiger als Serum.'},{t:'prevent-360', b:'magnesium', pct:82, note:'Magnesium im 360-Profil.'},{t:'longevity-check-up', b:'magnesium', pct:88, note:'Magnesium im Longevity-Panel.'},{t:'hautgesundheit-basis', b:'magnesium', pct:85, note:'Magnesium im Hautgesundheits-Panel.'},
  // Zink
  {t:'vollblutmineralanalyse', b:'zink', pct:97, note:'Zink intrazellulär.'},{t:'om-vital', b:'zink', pct:82, note:'Zink im OM-Vital-Panel.'},{t:'prevent-360', b:'zink', pct:80, note:'Zink im 360-Profil.'},{t:'hautgesundheit-basis', b:'zink', pct:90, note:'Zink im Hautgesundheits-Panel.'},{t:'longevity-check-up', b:'zink', pct:86, note:'Zink im Longevity-Panel.'},
  // Selen
  {t:'vollblutmineralanalyse', b:'selen', pct:97, note:'Selen intrazellulär.'},{t:'om-vital', b:'selen', pct:88, note:'Selen im OM-Vital.'},{t:'hautgesundheit-basis', b:'selen', pct:85, note:'Selen im Hautgesundheits-Panel.'},{t:'longevity-check-up', b:'selen', pct:84, note:'Selen im Longevity-Panel.'},
  // Eisen/Ferritin
  {t:'vollblutmineralanalyse', b:'eisen', pct:94, note:'Eisen intrazellulär.'},{t:'om-vital', b:'eisen', pct:88, note:'Ferritin im OM-Vital-Panel.'},{t:'hautgesundheit-basis', b:'eisen', pct:82, note:'Eisen im Hautgesundheits-Panel.'},{t:'longevity-check-up', b:'eisen', pct:85, note:'Eisen im Longevity-Panel.'},
  // Histamin/DAO
  {t:'histamin-dao-analyse', b:'histamin', pct:97, note:'DAO-Aktivität + Histamin (Stuhl) direkt.'},{t:'darmmikrobiom-analyse', b:'histamin', pct:82, note:'Histamin (Stuhl) im Mikrobiom-Panel.'},{t:'prevent-360', b:'histamin', pct:75, note:'Histamin/Histidin im 360-Profil.'},{t:'darmgesundheit-check-up', b:'histamin', pct:88, note:'Histamin im Darm-Paket.'},
  // Omega-3
  {t:'omega-3-test-fettsaure-analyse', b:'omega-3', pct:97, note:'EPA+DHA in Erythrozyten – Goldstandard.'},{t:'prevent-360', b:'omega-3', pct:72, note:'Omega-3-Index im 360-Profil.'},{t:'longevity-check-up', b:'omega-3', pct:88, note:'EPA/DHA im Longevity-Panel.'},
  // Tryptophan
  {t:'tryptophan-metabolismus', b:'tryptophan', pct:97, note:'Tryptophan + Kynurenin-Weg vollständig.'},{t:'prevent-360', b:'tryptophan', pct:82, note:'Tryptophan im Aminosäureprofil.'},{t:'darmgesundheit-check-up', b:'tryptophan', pct:75, note:'Tryptophan im Darm-Paket.'},{t:'longevity-check-up', b:'tryptophan', pct:80, note:'Tryptophan im Longevity-Panel.'},
  // Vitamin B6
  {t:'prevent-360', b:'vitamin-b6', pct:82, note:'B6 im 360-Profil.'},{t:'om-vital', b:'vitamin-b6', pct:70, note:'B6 indirekt über Neurotransmitter-Metabolite.'},
  // Folsäure
  {t:'vitamincheck-basis', b:'folsaeure', pct:96, note:'Folsäure direkt.'},{t:'om-vital', b:'folsaeure', pct:88, note:'Folsäure im OM-Vital.'},{t:'prevent-360', b:'folsaeure', pct:85, note:'Folat im 360-Profil.'},
  // Melatonin
  {t:'melatonin', b:'melatonin', pct:97, note:'Melatonin aus Nacht-Speichel – einziger direkter Test.'},{t:'schlaf-stress-paket', b:'melatonin', pct:92, note:'Melatonin im Schlaf-Stress-Paket.'},
  // Vitamin E
  {t:'vitamincheck-basis', b:'vitamin-e', pct:95, note:'Vitamin E (Tocopherol) direkt.'},{t:'om-vital', b:'vitamin-e', pct:88, note:'Vitamin E im OM-Vital.'},{t:'prevent-360', b:'vitamin-e', pct:78, note:'Vitamin E im 360-Profil.'},
  // CoQ10
  {t:'vitamincheck-basis', b:'coq10', pct:95, note:'CoQ10 (Ubiquinol) direkt.'},{t:'om-vital', b:'coq10', pct:88, note:'CoQ10 im OM-Vital.'},
  // Kupfer
  {t:'vollblutmineralanalyse', b:'kupfer', pct:97, note:'Kupfer intrazellulär.'},{t:'om-vital', b:'kupfer', pct:88, note:'Kupfer im OM-Vital.'},{t:'hautgesundheit-basis', b:'kupfer', pct:85, note:'Kupfer im Hautgesundheits-Panel.'},
  // Calcium
  {t:'vollblutmineralanalyse', b:'calcium', pct:97, note:'Calcium intrazellulär.'},{t:'hautgesundheit-basis', b:'calcium', pct:82, note:'Calcium im Hautgesundheits-Panel.'},
  // Natrium/Kalium
  {t:'vollblutmineralanalyse', b:'natrium-kalium', pct:97, note:'Na + K intrazellulär.'},
  // TSH/Schilddrüse
  {t:'om-vital', b:'tsh-schilddruese', pct:92, note:'TSH im OM-Vital-Screening.'},{t:'prevent-360', b:'tsh-schilddruese', pct:75, note:'TSH im 360-Profil.'},
  // hsCRP
  {t:'om-vital', b:'hscrp-entzuendung', pct:94, note:'hsCRP im OM-Vital.'},{t:'prevent-360', b:'hscrp-entzuendung', pct:88, note:'hs-CRP im 360-Profil.'},{t:'longevity-check-up', b:'hscrp-entzuendung', pct:85, note:'Entzündungsmarker im Longevity-Panel.'},
  // Cholesterin
  {t:'om-vital', b:'cholesterin-lipide', pct:94, note:'Vollständiges Lipidprofil im OM-Vital.'},{t:'prevent-360', b:'cholesterin-lipide', pct:85, note:'Cholesterin + Triglyzeride im 360-Profil.'},
  // Homocystein
  {t:'prevent-360', b:'homocystein', pct:88, note:'Homocystein im 360-Profil – Methylierungs-Check.'},{t:'om-vital', b:'homocystein', pct:78, note:'Homocystein im OM-Vital.'},
  // Jod
  {t:'jod-1', b:'jod', pct:97, note:'Jod-Ausscheidung im Morgenurin.'},{t:'prevent-360', b:'jod', pct:68, note:'Selen-Dejodase-Status aus Selen+TSH ableitbar.'},
  // 8-OHdG
  {t:'zellstressprofil', b:'8-ohdg-zellstress', pct:97, note:'8-OHdG direkt im Urin.'},{t:'organische-saure', b:'8-ohdg-zellstress', pct:85, note:'8-OHdG im organischen Säureprofil.'},{t:'schlaf-stress-paket', b:'8-ohdg-zellstress', pct:90, note:'8-OHdG im Stress-Schlaf-Paket.'},{t:'longevity-check-up', b:'8-ohdg-zellstress', pct:88, note:'DNA-Stabilität im Longevity-Panel.'},
  // IgG
  {t:'igg-lebensmitteltest', b:'igg-nahrungsmittel', pct:97, note:'270 Lebensmittel-IgG-Antikörper.'},{t:'darmgesundheit-check-up', b:'igg-nahrungsmittel', pct:72, note:'Immunreaktion im Darm-Paket.'},
  // Gluten
  {t:'gliadin-tg2', b:'gluten-zoeliakie', pct:97, note:'Anti-Gliadin + Anti-TG2 direkt.'},{t:'darmgesundheit-check-up', b:'gluten-zoeliakie', pct:65, note:'Gliadin-Antikörper im Darm-Paket.'},
  // Laktose
  {t:'laktose-atemtest', b:'laktose', pct:97, note:'H₂-Atemtest nach Laktose-Belastung.'},{t:'darmgesundheit-check-up', b:'laktose', pct:68, note:'Laktose-Intoleranz im Darm-Paket.'},
  // Mikrobiom
  {t:'darmmikrobiom-analyse', b:'mikrobiom', pct:96, note:'Mikrobiom-Komposition, Zonulin, Dysbiose.'},{t:'mikrobolom', b:'mikrobiom', pct:92, note:'Molekulargenetische Mikrobiom-Analyse.'},{t:'darmgesundheit-check-up', b:'mikrobiom', pct:90, note:'Mikrobiom im Darm-Paket.'},{t:'hautgesundheit-basis', b:'mikrobiom', pct:85, note:'Mikrobiom im Haut-Panel.'},{t:'longevity-check-up', b:'mikrobiom', pct:82, note:'Mikrobiom im Longevity-Panel.'},
  // SIBO/Verdauung
  {t:'sibo', b:'verdauungsenzyme-sibo', pct:97, note:'SIBO-Atemtest Goldstandard H₂/CH₄.'},{t:'darmgesundheit-check-up', b:'verdauungsenzyme-sibo', pct:88, note:'SIBO im Darm-Paket.'},{t:'laktose-atemtest', b:'verdauungsenzyme-sibo', pct:72, note:'Laktose-Atemtest zeigt Dünndarm-Funktion.'},{t:'fruktose-atemtest', b:'verdauungsenzyme-sibo', pct:68, note:'Fruktose-Atemtest zeigt Dünndarm-Transport.'},
  // Testosteron
  {t:'mann-hormonprofil-test', b:'testosteron', pct:97, note:'Testosteron aus Speichel.'},{t:'cortisol-tagesprofil', b:'testosteron', pct:72, note:'Cortisol/Testosteron-Antagonismus sichtbar.'},{t:'hormonprofil-frau', b:'testosteron', pct:85, note:'Testosteron im Frauen-Profil.'},{t:'hautgesundheit-basis', b:'testosteron', pct:78, note:'Testosteron im Haut-Panel.'},{t:'longevity-check-up', b:'testosteron', pct:90, note:'Testosteron im Longevity-Panel.'},
  // Östrogen
  {t:'hormonprofil-frau', b:'oestrogen', pct:97, note:'Estradiol + Progesteron im Frauen-Profil.'},{t:'beta-glucuronidase', b:'oestrogen', pct:82, note:'ß-Glucuronidase reaktiviert Östrogen.'},{t:'longevity-check-up', b:'oestrogen', pct:88, note:'Estradiol im Longevity-Panel.'},{t:'mann-hormonprofil-test', b:'oestrogen', pct:82, note:'Estradiol im Mann-Profil.'},
  // H. pylori
  {t:'helicobacter-pylori', b:'helicobacter', pct:97, note:'H. pylori-Antigen direkt.'},{t:'darmgesundheit-check-up', b:'helicobacter', pct:55, note:'H. pylori im Darm-Paket.'},
  // Kynurenin/NAD
  {t:'tryptophan-metabolismus', b:'kynurenin-nad', pct:97, note:'Vollständiges Kynurenin-Profil + NAD.'},{t:'organische-saure', b:'kynurenin-nad', pct:72, note:'Kynurensäure + Quinolinsäure im OA-Profil.'},{t:'schlaf-stress-paket', b:'kynurenin-nad', pct:65, note:'Kynurenin-Marker im Stress-Paket.'},{t:'longevity-check-up', b:'kynurenin-nad', pct:80, note:'NAD im Longevity-Panel.'},
  // ß-Glucuronidase
  {t:'beta-glucuronidase', b:'beta-glucuronidase', pct:97, note:'ß-Glucuronidase-Aktivität direkt.'},{t:'darmmikrobiom-analyse', b:'beta-glucuronidase', pct:68, note:'Dysbiose-Marker im Mikrobiom-Panel.'},
  // Parasiten
  {t:'profil-parasiten-pcr', b:'parasiten', pct:97, note:'6 Parasiten per Multiplex-PCR.'},{t:'darmgesundheit-check-up', b:'parasiten', pct:75, note:'Parasiten im Darm-Paket.'},{t:'mikrobolom', b:'parasiten', pct:55, note:'Parasiten-Screening im Mikrobolom.'},
  // Calprotectin
  {t:'darmgesundheit-check-up', b:'calprotectin', pct:88, note:'Calprotectin im Darm-Paket.'},{t:'darmmikrobiom-analyse', b:'calprotectin', pct:72, note:'Calprotectin im Mikrobiom-Panel.'},{t:'mikrobolom', b:'calprotectin', pct:60, note:'Immunfunktion im Mikrobolom.'},
  // Zonulin
  {t:'darmmikrobiom-analyse', b:'zonulin', pct:94, note:'Zonulin direkt im Stuhl.'},{t:'darmgesundheit-check-up', b:'zonulin', pct:88, note:'Zonulin im Darm-Paket.'},{t:'gliadin-tg2', b:'zonulin', pct:65, note:'Gluten aktiviert Zonulin.'},{t:'mikrobolom', b:'zonulin', pct:60, note:'Barrierefunktion im Mikrobolom.'},
];

async function run() {
  console.log('🚀 Starting migration...\n');

  // 1. Insert tests
  console.log('📋 Inserting tests...');
  const testsData = TESTS.map(t => ({
    id: t.id, name: t.name, price: t.price, sub: t.sub, sample: t.sample,
    shop_slug: t.shop_slug, cat: t.cat, cat_key: t.cat_key,
    tags: t.tags, keywords: t.keywords, description: t.description,
    biomarker_names: t.biomarker_names
  }));
  
  const { error: te } = await sb.from('bm_tests').upsert(testsData, {onConflict:'id'});
  if (te) { console.error('Tests error:', te.message); return; }
  console.log(`✅ ${TESTS.length} tests inserted`);

  // 2. Insert biomarkers
  console.log('🔬 Inserting biomarkers...');
  const bmData = BIOMARKERS.map(b => ({
    slug: b.slug, name: b.name, aliases: b.aliases,
    description: b.description, symptoms: b.symptoms,
    cofaktoren: b.cofaktoren
  }));

  const { error: bme } = await sb.from('bm_biomarkers').upsert(bmData, {onConflict:'slug'});
  if (bme) { console.error('Biomarkers error:', bme.message); return; }
  console.log(`✅ ${BIOMARKERS.length} biomarkers inserted`);

  // 3. Fetch biomarker IDs
  const { data: bms } = await sb.from('bm_biomarkers').select('id, slug');
  const slugToId = Object.fromEntries(bms.map(b => [b.slug, b.id]));

  // 4. Insert mappings
  console.log('🔗 Inserting mappings...');
  const mappingData = MAPPINGS.map(m => ({
    test_id: m.t,
    biomarker_id: slugToId[m.b],
    coverage_pct: m.pct,
    note: m.note
  })).filter(m => m.biomarker_id);

  const { error: me } = await sb.from('bm_test_biomarkers').upsert(mappingData, {onConflict:'test_id,biomarker_id'});
  if (me) { console.error('Mappings error:', me.message); return; }
  console.log(`✅ ${mappingData.length} mappings inserted`);

  // 5. Verify
  const { count: tc } = await sb.from('bm_tests').select('*', {count:'exact',head:true});
  const { count: bc } = await sb.from('bm_biomarkers').select('*', {count:'exact',head:true});
  const { count: mc } = await sb.from('bm_test_biomarkers').select('*', {count:'exact',head:true});
  
  console.log('\n📊 Database summary:');
  console.log(`   Tests:     ${tc}`);
  console.log(`   Biomarkers: ${bc}`);
  console.log(`   Mappings:  ${mc}`);
  console.log('\n✅ Migration complete!');
}

run().catch(console.error);
